### ISSUE TITLE
Returning an array from bind.js, instead of a string

### ISSUE THREAD

**Issue by juice49** [JedWatson/classnames#101]
Classnames almost works with React Native's StyleSheet module, using the bind variant. The one problem is that in React Native, the style attribute expects an array of keys instead of the string you'd pass to the className attribute of React.

I was able to get `bind.js` to work with React Native by returning the array of classes instead of [joining it](https://github.com/JedWatson/classnames/blob/master/bind.js#L35).

Here's an example React Native component using Classnames (assuming classNames is returning an array):

``` js
import React, { Component } from 'react'
import { StyleSheet, Text, TouchableOpacity } from 'react-native'
import classNames from 'classnames/bind'

const cx = classNames.bind(StyleSheet.create({
  button: {
    padding: 4,
    backgroundColor: '#fff'
  },
  'button--dark': {
    backgroundColor: '#000'
  }
}))

const Button = ({ children, primary }) => {

  const style = cx('button', {
    'button--dark': primary
  })

  return ( 
    <TouchableOpacity style={style}>
      <Text>
        {children}
      </Text>
    </TouchableOpacity>
  )

}
```

I wanted to PR with an update to `bind.js` that allows an array to be returned instead of a string, but I couldn't think of a good way to achieve this without duplicating the entire `bind.js` file. It seems like a shame to duplicate so much for such a small change.

There's no (good) way to pass a config argument to `classNames()`, as arguments are used exclusively for classnames and conditions. It's also not possible to set a flag on `this`, because it's exclusively used for the styles object.

I had some other ideas about how to achieve this, but they seem impractical or just aren't possible for one reason or another:

A. Export a factory from `bind.js` that accepts styles and config, i.e. `const cx = classNames(styles, { returnArray: true })`. Impractical as it changes the existing API.

B. Move the majority of the code from `bind.js` into another file that could be shared by `bind.js` and a variant `bind-array.js`. This would avoid duplication, but means Classnames would need to be built to UMD from source files.

C. Split the output string on `'  '`, either in a function exported by Classnames, or in the consumer. Probably not ideal for performance, although I don't know for sure. If done in the consumer, it assumes that Classnames is joining on `'  '` (and will break if this changes).

D. Have `bind.js` recognise a config constant or symbol that could be passed in the styles object, or bound to `this`. Feels like a hack.

Any thoughts on this? Am I missing something obvious? Would this functionality even be welcome in Classnames? 😊

**Comment by dcousens** [comment]
I don't know if this module is really that useful if you have an array of keys?

**Comment by michaelzoidl** [comment]
Hey, i think @juice49 meant something like the `classnames` module creates a new string from the arguments it receives, but react-native expects an array of objects with the stylings instead of an array, so its kind a similar to the `bind.js` file, but this one also just returns a string.

IMO adding this function to the `bind.js` would make it more complicated, either there should be a new file (something like `classnames/react-native`) or outsource it into an separated repo, i prefer the second solution, so i made [rn-classnames](https://github.com/entwicklerstube/rn-classnames)

@dcousens you can checkout the project, do you think it would make sense to make a note in the README for other react-native developer? :)
