### ISSUE TITLE
Bundle TypeScript definitions

### ISSUE THREAD

**Issue by bradleyayers** [JedWatson/classnames#102]
Would you be open to bundling a .d.ts TypeScript definition for this package, so that it can seamlessly be used from TypeScript?

There are existing definitions https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/classnames that could be copied over, so it should be fairly trivial.

**Comment by dcousens** [comment]
@bradleyayers I'm not opposed to the idea,   its just a matter of the slippery slope.
Is there any reason why the `DefinitelyTyped` types wouldn't be suitable?

**Comment by bradleyayers** [comment]
I went the DefinitelyTyped route initially, but hit a blocker because my project has two transitive dependencies on `@types/classnames`, which pulls in two sets of definitions that conflict (because they're global definitions).

I don't know of another solution here other than bundling the declaration files in the npm package.

**Comment by dcousens** [comment]
@bradleyayers how will this solve that unless everyone uses this packages type definitions?

**Comment by bradleyayers** [comment]
I'm not sure I understand the question, but…

TypeScript automatically uses type definitions that are bundled in NPM packages, but someone could still use @types/classnames if they want (but they probably wouldn't want to, since it's more overhead).

The key difference with packaged definitions is that they don't need to introduce definitions globally. This means that multiple instances of a package can be used at the same, each providing their own definitions.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/JedWatson/classnames/pull/103
