### ISSUE TITLE
padding={{direction: 'all', size: '1'}} using classnames?

### ISSUE THREAD

**Issue by andyngo** [JedWatson/classnames#107]
Hi, I'm trying to create a component that takes in some props similar to this:
```<Component padding={{direction: 'all', size: '1'}} />```

Any idea if this can be done with `classnames`?

I tried writing it this way but it didn't work:
```
const classes = classnames({
  'pa1': props.padding === {
    direction: 'all',
    size: '1',
   }
})
```
Any help here would be very much appreciated. Thanks in advance.

**Comment by dcousens** [comment]
@andyngo what?

What would you expect `classes` to be equal to in the above snippet?

**Comment by dcousens** [comment]
Oh wait,  maybe you just want something like https://www.npmjs.com/package/deep-equal?

Alternatively

```
'pa1': props.padding.direction === 'all' && props.padding.size === 1
```
