### ISSUE TITLE
Suggestion: Consider PropTypes Example (Documentation)

### ISSUE THREAD

**Issue by zacanger** [JedWatson/classnames#108]
Would you consider adding an example of `PropTypes` that work with this lib to the README?
This could be very useful for someone making low-level components that use `classnames`, that can get passed anything compatible by a higher component.

An example might be:

```javascript
import { PropTypes } from 'react'
import classNames from 'classnames'

export const classname = PropTypes.oneOfType([
  PropTypes.object,
  PropTypes.string,
  PropTypes.arrayOf(
    PropTypes.oneOfType([
      PropTypes.array,
      PropTypes.bool,
      PropTypes.object,
      PropTypes.string
    ])
  )
])

const Foo = ({ className }) => (
  <div className={classNames(className)} />
)

Foo.propTypes = {
  className: classname
}
```

I can PR for this if it seems like a good idea.

**Comment by Amberlamps** [comment]
This is not a good idea. `classnames` is returning a string. Why don't you just pass that string to our component? Not only is the prop types definition easy then

```
Foo.propTypes = {
  className: PropTypes.string.isRequired
};
```

but also your stateless component stays pure. The component in your example is not pure.
