### ISSUE TITLE
Importing classnames installed via NPM while using Webpack

### ISSUE THREAD

**Issue by ramarivera** [JedWatson/classnames#111]
Hi, firstly i'd like to thank you and the comunity for this amazing module, it certainly makes the life of anyone coding in React easier.

It seems i'm doing something wrong, yet i cant find what it is. You see, i'm coding in React with Typescript, therefore, i use
`import * as ClassNames from "classnames"`
to import your module into my code, but webpack seems unable to include it in the output bundle, forcing me to include it as a separate asset in my html. While this isn't terribly annoying, it would be wonderfull if classnames could be bunbled with the rest of my code.

I hope you can help me, either by telling what i'm doing wrong or by showing me how to hack around this.
Thanks in advanced!!

**Comment by dcousens** [comment]
I'm not familiar with webpack to this degree,  maybe @AndyOGo could help

**Comment by AndyOGo** [comment]
@ramarivera 
@dcousens 

Sure I can help out.
@ramarivera your syntax is wrong, make sure to read the docs and understand how `import` works.
Especially default imports as described in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Importing_defaults

Correct code would be in your case:
````js
import classNames from 'classnames'
````

**Comment by ramarivera** [comment]
I tried that, but Typescript compiler says
`Module '"classnames"' has no default export.`

Just tried it again but got same results :/
(Thanks for the speedy reply!)

**Comment by AndyOGo** [comment]
That's strange, I mean I use Babel, but that is really weird...

**Comment by AndyOGo** [comment]
found https://github.com/Microsoft/TypeScript/issues/3337

**Comment by ramarivera** [comment]
I tried changing the syntax to what that thread provides, to no avail. I also changed my typescript loader from awesome-typescript-loader to ts-loader as suggested but it doesnt work either :(

**Comment by AndyOGo** [comment]
@ramarivera 

I'm just curious, may I ask you to try this:

````js
import classNames from 'classNames';
````

If that works, it is related to another bug I issues months ago:
https://github.com/JedWatson/classnames/issues/82#issuecomment-218676799

**Comment by ramarivera** [comment]
Nope :( it says that no module with that name can be found

**Comment by AndyOGo** [comment]
If the above does not fix it, I found this issue:
[https://github.com/Microsoft/TypeScript/issues/11179](Importing commonJS modules with es6 imports)

**Comment by mikestead** [comment]
@ramarivera Did you install the latest typings? `npm install @types/classnames --save-dev`

**Comment by ramarivera** [comment]
I can´t be sure of which of all the things i tried yesterday was, but something fixed it and now it's getting bundled correctly. Again, thanks for the quick replies and sorry for "wasting" your time 👍

**Comment by zposten** [comment]
Because there's not really an "answer" on this thread, I wanted to supply the one that worked for me:

```ts
import * as classnames from 'classnames'
```

**Comment by havivi** [comment]
Thx @zposten !!! import * as classnames from 'classnames' works for me too.

**Comment by jcousins-ynap** [comment]
Whilst this gets rid of the original error I now get

```js
classnames__WEBPACK_IMPORTED_MODULE_3__ is not a function

TypeError: classnames__WEBPACK_IMPORTED_MODULE_3__ is not a function
    at MyComponent (http://localhost:9009/main.6dc20d2f7c98431509a6.bundle.js:353:740)
    at renderWithHooks (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:48679:18)
    at mountIndeterminateComponent (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:50761:13)
    at beginWork (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:51366:16)
    at performUnitOfWork (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:55053:12)
    at workLoop (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:55093:24)
    at renderRoot (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:55176:7)
    at performWorkOnRoot (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:56083:7)
    at performWork (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:55995:7)
    at performSyncWork (http://localhost:9009/vendors~main.6dc20d2f7c98431509a6.bundle.js:55969:3)
```

**Comment by shawfire** [comment]
I'm using typescript with React and this works for me:
npm i -D @types/classnames
import classNames from 'classnames';
