### ISSUE TITLE
What's the order of application of classes?

### ISSUE THREAD

**Issue by hyperh** [JedWatson/classnames#112]
I'm using CSS modules, Is there a guaranteed order of application of CSS classes? In the following example, can I expect the resultant style to always have a green background since `.bar` is last? I'm getting inconsistent results in my app. Is there a way to enforce order of application then?

```
// main.css
.foo {  background: red; }
.bar { background: green; }
```

```
// main.js
import styles from './main.css';
const style = classNames(styles.foo, styles.bar);
```

**Comment by Amberlamps** [comment]
Order is guaranteed: https://github.com/JedWatson/classnames/blob/master/index.js#L16
What kind of inconsistencies are you experiencing?

**Comment by hyperh** [comment]
@Amberlamps It might have been a CSS modules `composes` issue actually. But thanks for the answer, at least I know that classnames guarantees class application order.

**Comment by hosseinmd** [comment]
Order of class names is not correct.
Imagine we have this:
``` className='foo bar' ```

If we use this module there is a problem.
``` className= classNames('foo','bar') // return 'bar foo' ```

Class names should be reversed.

**Comment by newyork-anthonyng** [comment]
@hosseinmd can you provide an example of this?

https://codesandbox.io/s/vigilant-smoke-cnogr?file=/src/App.js

I created a codesandbox for this; it works as expected.

**Comment by charkour** [comment]
This is happening when using classnames with postcss modules. 

I have something like this. 

```tsx
import s from './Button.module.css';
import cn from 'classnames';

    const rootClassName = cn(
        s.root,
        {
            [s.primary]: variant === 'primary',
            [s.secondary]: variant === 'secondary',
        },
        className
    );
```

If `className` is a string, then it is applied before the css modules with posts are applied, even though I specify that `className` should be the last thing applied in the function.

**Comment by rodoabad** [comment]
@charkour looks like order is not guaranteed based on your post.

**Comment by charkour** [comment]
Hey @rodoabad, thanks for your comment, but I'm not quite sure what you mean.

After using `classnames` and `clsx` for a year now, I believe the reason that `className` is applied after the CSS module is due to specificity. The CSS module has higher specificity than the `className` string passed to the `cn()`.

**Comment by samerset-rmn** [comment]
Hi there! Have you guys found any solution yet? I've just stumbled upon the same issue. Thinking how to prioritize the string classname over CSS module.
