### ISSUE TITLE
[Request] remove a className easely

### ISSUE THREAD

**Issue by kopax** [JedWatson/classnames#113]
I am looking to do something like this : 

      cn('form-control toto', {
        'form-control': false,
      });

but this doesn't remove `form-control`.
Would be nice to be able to negate a class.

**Comment by dcousens** [comment]
Probably not in scope to be honest.

**Comment by fmal** [comment]
@kopax https://github.com/JedWatson/classnames#alternate-dedupe-version

**Comment by dcousens** [comment]
Of course.
