### ISSUE TITLE
Return of empty string results in class=""

### ISSUE THREAD

**Issue by interactivellama** [JedWatson/classnames#115]
I can wrap this function in a comparison function and make `className` `undefined` myself, but was wondering if this was the best way. I'd looked through the issues and was surprised no one has raised this issue before.

In the real world, I'd probably wrap this library in a library level utility that does this and not repeat the object twice. This is of course specific to React which sees an empty string and `undefined` differently.

```
className={classNames({
				'slds-is-today': isToday,
				'slds-disabled-text': !isCurrentMonth,
				'slds-is-selected': isSelectedDay
			}) === '' ? undefined : classNames({
				'slds-is-today': isToday,
				'slds-disabled-text': !isCurrentMonth,
				'slds-is-selected': isSelectedDay
			})
```

**Comment by dcousens** [comment]
Excellent question,  but unfortunately changing it would be API incompatible as many users use concatenation with other strings post-haste which would cause `"undefined"` to be concatenated if changed now.

**Comment by interactivellama** [comment]
Completely agree. It'd probably only make sense if you could do something like:

```
import { classNameUndefined as className } from 'classname'
```

**Comment by dcousens** [comment]
We accept alternative behaviours submitted as independent sub-modules:  `classnames/undefined` etc

**Comment by interactivellama** [comment]
By independent, do you mean:
1. copy and paste `index.js`
1. create a `joinedClasses` variable
1. add an if statement at the end right before the return

Does `classnames/empty-as-undefined` sound good for a module name or do you all like one word, more-ambiguous names?

**Comment by dcousens** [comment]
Yes.

> `classnames/empty-as-undefined`

It does the job for now.
I can't guarantee that this will be `npm` released as @JedWatson is inactive [here].

The primary purpose is that separate modules will have zero impact on existing users,  even in bundling.

**Comment by interactivellama** [comment]
The last release was May 2, 2016. Will you tag/release if I provide a pull request? I'm willing to point to a Github tag if needed, but wouldn't be willing to point to a commit.

**Comment by dcousens** [comment]
@interactivellama I am willing to put a Github tag.

**Comment by Noitidart** [comment]
I had this exact same issue today haha! I'm like why the heck are there all these blank `class` attributes. I did this for now:

file: `react-classnames`
```
// classnames returns blank string when it fails, it should be returned undefined for react
import classnames from 'classnames';

const classnamesUndefined = (...args) => classnames(...args) || undefined;

export default classnamesUndefined;
```

**Comment by interactivellama** [comment]
I'm going to something similar internally. This can be closed, or kept open to allow someone else to take up the mantle. Thanks.

**Comment by zordius** [comment]
i created a tiny package for this: https://www.npmjs.com/package/classnames-undefined
