### ISSUE TITLE
Undefined is rendered as class name (should this happen?)

### ISSUE THREAD

**Issue by smiket** [JedWatson/classnames#118]
Hi,

I'm using react props to allow a parent component to pass an optional class to child component.
In the child, I'm using computed key syntax in the classNames call:

        const cssClassNames = classNames({
            'ese-menu-item': true,
            [this.props.cssClass]: true,
        });

If the parent does not pass a value for cssClass (its optional) the child prop is undefined.
This renders as:  class="ese-menu-item undefined"
Perhaps this item could be skipped when no value is present?

I could see the existing behavior as being correct, but wanted to at least raise the issue for consideration.
If you think it's ok as-is, I would not disagree -
Thanks for this library - it's very nice.

Steve

**Comment by newyork-anthonyng** [comment]
@smiket There's a simpler way to get the intended effect you want. Please note that
* `classNames` accepts `string` arguments
* `classNames` ignores falsey values

The code snippet below should give you the intended effect you are looking for.
```js
const cssClassNames = classnames('ese-menu-item', this.props.cssClass);
```

I hope that helps!

**Comment by xixilive** [comment]
👍

**Comment by bubokko** [comment]
I had the same issue, but it's not `classname`'s fault. The `{[undefined]: true}` is interpreted in JavaScript as `{"undefined": true}`, so it's a string already before `classnames` even gets that value. A workaround I decided to use is:

```javascript
const cssClassNames = classNames({
    'ese-menu-item': true,
    [this.props.cssClass ?? ""]: true,
});
```

So `undefined` class names will be transformed to empty strings, which are properly ignored by `classnames`.
