### ISSUE TITLE
Proposal: Expose classNames, bind and dedupe within a single object in index.js

### ISSUE THREAD

**Issue by dlicul** [JedWatson/classnames#121]
This is similar to #82 

The problem occurs when an application wants to use all three flavors of classNames; regular, bind and dedupe. At the moment window.classNames is exposed with a same name in all three files. So entire application must settle only on one option but that is not optimal if dedupe is only needed in say 2 react components but the rest of components need only regular or bind version.

I've created a fork here 
[https://github.com/dlicul/classnames/tree/feature/merge-files](https://github.com/dlicul/classnames/tree/feature/merge-files)

This is a breaking change but allows all three flavors to run in the browser when bundling with webpack or browserify.

var classNames = require('classNames')
classNames.set(...)
classNames.setBound.bind(....)
classNames.dedupe(....)

**Comment by dcousens** [comment]
Unfortunately this is a result of the AMD? support that was shoe-horned into each file when it should have been done separately.
@JedWatson we knew this would bite at some point.

@dlicul I'd prefer to just remove the inline AMD support and move that honus onto the user.
Breaking change either way.

**Comment by dcousens** [comment]
Relevant PR (where it all started): https://github.com/JedWatson/classnames/pull/30

**Comment by dcousens** [comment]
Closing in favour of https://github.com/JedWatson/classnames/issues/82 - merging is not the approach to take here.
