### ISSUE TITLE
[Bug/Suggestion] Working with arguments object

### ISSUE THREAD

**Issue by lxkuz** [JedWatson/classnames#125]
If we will use `classnames` with `arguments` object inside a function we get strange behavior
```javascript
var func = function(a, b, c) { 
  return classnames(arguments)
}

func("a", "b", "c"); // => "0 1 2"

```

**Comment by lxkuz** [comment]
@JedWatson I have fixed it and tests are ready. I have to inspect benchmarks to complete this issue.

**Comment by newyork-anthonyng** [comment]
@lxkuz The `arguments` object in your example would look like this:
```js
{
  0: 'a',
  1: 'b',
  2: 'c',
}
``` 
This explains why your `classnames` results in `0 1 2`.

You could fix this by converting `arguments` into a real array before passing it into `classnames`.
```js
var func = function(a, b, c) {
  const newArgs = Array.prototype.slice.call(arguments);
  return classnames(newArgs);
}

func('a', 'b', 'c'); // => 'a b c'
```

**Comment by lxkuz** [comment]
@newyork-anthonyng Yes, it's true. But when I researched arguments to array conversion I found this information  https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments
It looks like your sample of code will kill V8 optimization. Now I have
```javascript
const newArgs = Array.from(arguments) 
```
And I know it is wrong (not supported for old Node.js versions and maybe will kill V8 optimization too). I am going to use this way (workaround from Optimization-killers page's sample):
```javascript
const i = arguments.length
let newArgs = []
while (i--) newArgs[i] = arguments[i]
```
What do you thinking about it?

**Comment by newyork-anthonyng** [comment]
@lxkuz I'm not too familiar with optimizing for the `arguments` object, but your code snippet looks good! 👍

**Comment by lxkuz** [comment]
Done

**Comment by newyork-anthonyng** [comment]
@lxkuz I meant that you could use that code snippet (where you expand your `arguments`object into a real array) on your client code.

See this closed [issue](https://github.com/JedWatson/classnames/issues/22).

**Comment by lxkuz** [comment]
@newyork-anthonyng  oh yes, I can see. Thanks.
