### ISSUE TITLE
[Suggestion] Drop duplicate class names

### ISSUE THREAD

**Issue by lxkuz** [JedWatson/classnames#127]
I suggest changing this:
```javascript
classnames(["a", "b", "a", "b"]) // => "a b a b"
```
for this:
```javascript
classnames(["a", "b", "a", "b"]) // => "a b"
```

**Comment by newyork-anthonyng** [comment]
@lxkuz I believe this is what the `dedupe` version does. See the [README](https://github.com/JedWatson/classnames#alternate-dedupe-version).

**Comment by newyork-anthonyng** [comment]
@lxkuz Was the `dedupe` version what you were looking for? Could we close this issue?

**Comment by lxkuz** [comment]
Yes just forgot it, thanks.
