### ISSUE TITLE
Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by drewbietron** [JedWatson/classnames#129]
This error keeps popping up in IE 11.  Apparently using JavaScript to apply CSS to Internet Explorer/Edge returns ‘Assignment to read-only properties is not allowed in strict mode’.

**Comment by dcousens** [comment]
Can you provide a code sample

**Comment by newyork-anthonyng** [comment]
@drewbietron `classNames` is simply creating a string for you to use. 

Like @dcousens said, `classNames` is most likely not the culprit of this error message. I'm very interested in seeing the code snippet that recreates this error.

**Comment by arcman77** [comment]
@drewbietron is correct. 
https://devtidbits.com/2016/06/12/assignment-to-read-only-properties-is-not-allowed-in-strict-mode/#comment-1611

Apparently you're supposed to use this something like `myEle.style.cssText = "color: red;"`

However I still get the same error even after applything that fix...

**Comment by drewbietron** [comment]
Any consideration to re-opening this issue?
