### ISSUE TITLE
improved css modules method

### ISSUE THREAD

**Issue by tswaters** [JedWatson/classnames#130]
The way to go about css modules seems to be using the `bind` method.

This takes an object that will be used as a map to lookup the actual className from the result of a css module export.  The way in which it does this is instead of the property key, it will do a lookup against `this` and use the result (or the key if it wasn't found)

This is somewhat limiting as you can't combine multiple sources.  It would be valuable to provide a mechanism to attach multiple objects.  The use case would be using a combination of css frameworks in addition to one's own styles.  Presently multiple functions need to be created and used independently: 

```js
import classNames from 'classnames/bind'
import * as bootstrap from 'bootstrap/less/bootstrap'
import * as fontawesome from 'font-awesome/less/font-awesome'
import styles from './styles.css'

const bs = classNames.bind(bootstrap)
const fa = classNames.bind(fontawesome)
const cx = classNames.bind(styles)

bs('col-xs-12', 'col-xs-6')
fa('fa', 'fa-user')
cx('my-style')
```

It would be cool if this could be simplified into a single call.. off the top of my head, I've called it `join`  and placed it next to `bind`, but this could be named anything and placed anywhere, really...

e.g.:

```js
import classNames from 'classnames/bind'

const cx = classNames.join(bootstrap, fontawesome, styles)

cx('col-xs-12', 'col-sm-6')
cx('fa', 'fa-user')
cx('my-style')
```

**Comment by newyork-anthonyng** [comment]
@tswaters 

Could you use the default `classNames` package to accomplish the same result?

```js
import cx from 'classnames';
import styles1 from './styles1.css';
import styles2 from './styles2.css';
import styles3 from './styles3.css';

cx(
  styles1.foo,
  styles2.bar,
  styles3.baz,
);
```

**Comment by dcousens** [comment]
Interesting idea,  but this could be done at a higher level.
Maybe play with the idea as a sub-module.... but tbh,  I think @newyork-anthonyng's idea is better off semantically then doing constant key lookups.

**Comment by tswaters** [comment]
Probably correct.  After playing / thinking on it a bit, I'll probably switch to not using `bind` at all.  Eventually I hope to see css modules (by way of webpack's css-loader) use es6 modules and named exports, so ideally tree shaking could be a possibility...  running the entire export through bind is not exactly conducive to that.
