### ISSUE TITLE
Being able to spread in React {...cx('awesome-style')}

### ISSUE THREAD

**Issue by jeroenransijn** [JedWatson/classnames#132]
The idea I am playing with is to save a couple of characters of typing .
I am not sure if this really something worth pursuing, but it has been somewhat of an annoyance since I often mistype className and react props can quickly build up.

```jsx
import React from 'react'
import cx from 'classnames/react-spread'

// Only type className once inside the component
const MyComponent = ({ className, ...props }) =>
  <div {...cx(className, 'another-class')} />

// No need to type className at all
const MyOtherComponent = () => <div {...cx('awesome-style')} />
```

It would work exactly the same as classNames right now, but instead it would return an object:
```jsx
import cx from 'classnames/react-spread'

const obj = cx('magic') // => { className: 'magic' }
obj.className // => 'magic'
```

I was thinking of calling it something like `classnames/react-spread`.

If maintainers think this is a dumb idea, feel free to close this issue.

**Comment by newyork-anthonyng** [comment]
@jeroenransijn I have definitely typed in all variations of `className` into my JSX (`classnames`, `classname`, `classNames`, `className`). I wonder if I should use a better linter to catch these 🤔

Also, I think it would be simple to write your own wrapper around `classnames`, and use that instead. It would look something like:
```jsx
// wrappedClassname.js
import cx from 'classnames';

function wrappedClassname() {
  const newArgs = Array.prototype.slice.call(arguments);
  return {
    className: cx(newArgs),
  }
}

export default wrappedClassname;
```

**Comment by jeroenransijn** [comment]
@newyork-anthonyng I always get the wrong autocomplete for className. I am currently trying out something like this in combination with glamor:

```
import { css } from 'glamor'
import isPlainObject from 'lodash.isplainobject'
import cx from 'classnames'
import TextStyles from './TextStyles'

const cn = (...classes) => {
  return {
    className: cx(classes.map(x => {
      return isPlainObject(x) ? css(x).toString() : x
    }))
  }
}

const MyComp = props => <div {...props} />

MyComp.defaultProps = {
  ...cn(TextStyles.heading300, {
    '&:hover': {
      background: 'rgba(255, 255, 255, 0.2)'
    }
  })
}
```

Your example is pretty much what I had in mind.

**Comment by alexsasharegan** [comment]
I think @newyork-anthonyng has a solid answer. Could also skip a line and just apply the wrapper function arguments as well:

```js
// wrappedClassname.js
import cx from 'classnames';

function wrappedClassname() {
  return {
    className: cx.apply(null, arguments),
  }
}

export default wrappedClassname;
```

**Comment by mrchief** [comment]
If the main goal is to save characters while typing, a much better idea (IMHO), would be to use [classnames-loader](https://github.com/itsmepetrov/classnames-loader):

Without loader:
```jsx
import styles from './styles.css';
const cx = classNames.bind(styles);

...

<div className={cx('className')}>...
```

With loader:
```jsx
import cx from './styles.css';
...

<div className={cx('className')}>...
```

Of course, you can still pursue your idea to stave off few more characters on top of this! :)

**Comment by mayavera** [comment]
@jeroenransijn if you're having trouble with typing the correct name (as many of us do 🙇 ), I would recommend using [`eslint`](https://eslint.org) with [no-undef](https://eslint.org/docs/4.0.0/rules/no-undef) set to "warning" or "error". You can run `eslint` in a terminal next to your editor and it will tell you when you make mistakes like this. Optionally, you can integrate it with [VScode](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), [Atom](https://atom.io/packages/linter-eslint), or [Sublime Text](https://packagecontrol.io/packages/ESLint). I use it with VSCode and it's pure magic.

PS. Be sure to check out [`eslint --fix`](https://eslint.org/docs/user-guide/command-line-interface#--fix) for some extra special wizardry!

**Comment by dcousens** [comment]
If you wanted this as `/spreadable`,   or something,   OK,  but,  is this idiomatic?
