### ISSUE TITLE
Dynamic class name in ES2015 not working

### ISSUE THREAD

**Issue by alduro** [JedWatson/classnames#134]
I do have this:

```
const statusClasses = classnames(
       styles.statusRight,
       styles.statusButton,
       { [`styles.${ status }`]: true }, )
```

that generates:

```
<div class="Controls__statusRight--ee934205 Controls__statusButton--c9d96e3c styles.live">
```

What am I missing ? Thanks.

**Comment by webdeveloperpr** [comment]
maybe like this ?
` { [`${styles['status']}`]: true }`

**Comment by alduro** [comment]
@webdeveloperpr 👍 
without the quotes but yes !  ``` {[styles[status]]: true});  ```

**Comment by newyork-anthonyng** [comment]
@alduro Did you simplify your example so that `styles[status]` was always true?

If not, you could rewrite your code as:
```js
const statusClasses = classnames(
    styles.statusRight,
    styles.statusButton,
    styles[status]
);
```

**Comment by alduro** [comment]
@newyork-anthonyng yes ! I simplified  it that way.

**Comment by morajabi** [comment]
Why we can't use this: ```[`styles.${ status }`]```?
