### ISSUE TITLE
Support for styles generated using glamor

### ISSUE THREAD

**Issue by vamsiampolu** [JedWatson/classnames#136]
I came across an issue when consuming a project called ant-design along with glamor v2 and css. glamor generates an object instead of a string, so adding it a list of classes would cause no styling changes.

The original issue is here:

https://github.com/ant-design/ant-design/issues/6226

We might want to either  fix this issue if glamor allows checking if the object it generated is a style.

**Comment by newyork-anthonyng** [comment]
Hi @vamsiampolu,

I looked at your [WebpackBin link](https://www.webpackbin.com/bins/-Kn7PqDK39uc6VARw-vO) and the documentation for [glamor](https://github.com/threepointone/glamor).

It seems like `glamor.css()` is returning an object with a `toString` function.

```js
import { css } from 'glamor'

const scaryBorder = css({
  background: 'honeydew',
});

console.log(scaryBorder);
// { 'data-css-vkqpno': '', toString: someFunction() }
```

`classnames` is processing this object correctly. `data-css-vkqpno` has a `falsey` value (an empty string), and doesn't include it as part of its output. As far as I can tell, no code change is needed for this library.

Your fix that you had in your [issue](https://github.com/ant-design/ant-design/issues/6226#issuecomment-303570867) seems to be the right answer:
```js
const someClassName = cx('a', 'b', scaryBorder.toString());
```

I believe you can also simplify it by coercing your `scaryBorder` object into a string with template literals. This will call `toString`.
```js
const someClassName = cx('a', 'b', `${scaryBorder}`);
```

**Comment by vamsiampolu** [comment]
@newyork-anthonyng The last part about coercing to `string` did not occur to me. Thanks.

**Comment by helixbass** [comment]
@vamsiampolu I just ran into the same thing and I don't want to have to explicitly convert my `glamor.css()` value to a string before passing to `classNames()`, so I modified the `classNames()` function to be compatible with the output of `glamor.css()` (on the `glamor` branch of my fork of this repo). This was the change I added (before it checks if `arg` is a string or an object):
```
if (hasOwn.call(arg, 'toString')) {
  arg = arg.toString();
}
```
I assume this is not safe/performant enough to be considered for inclusion in the standard version, but if you want to use the glamor-compatible version, you could switch the dependency in your `package.json` to eg `"classnames": "github:helixbass/classnames#6fcc367"`
