### ISSUE TITLE
Local bind for css modules

### ISSUE THREAD

**Issue by scazzy** [JedWatson/classnames#137]
Suggestion: for ease of implementation at local components.
Using css-modules, and have used classnames at higher level for default/app-wide css, which exports a method called classNames (already bound with app wide css).

At local components, am doing
```
import classNames from '../styles'
import style from './style.scss'
```

But while using it, I can't use string keys for local styles. I've to either do a `style.class`, or `style['class']` if it contains hyphen.
Can I add local style to the same className or somehow that I can just use local styles as string keys instead of the repetitive array style.

**Comment by newyork-anthonyng** [comment]
@scazzy Have you taken a look at the `bind` version of `classnames`? See [documentation](https://github.com/JedWatson/classnames#alternate-bind-version-for-css-modules).

**Comment by scazzy** [comment]
@newyork-anthonyng Yes. The bind would return object map of the class hashes.
I'm currently using that to bind my global css.
What I was referring to is - to allow binding local css to the object that's already bound.

Currently, 
```
import classnames from 'classnames'; [1]
import globalStyles from '../../styles'; [2]
import style from './styles';


const cx = classnames.bind(globalStyles)
<Element className={cx('btn', style.class1, style['class-2'])}
```

If I could add/bind local (component level) css to the same cx, I could simply use
`cx('btn', 'localclassname')` instead of `style['class']`. // btn is global class

Note: Currently, I do [1] and [2] at the global style level, and simply import 'cx from '../../styles'

**Comment by mrchief** [comment]
Have you tried this?

```jsx
import globalStyles from '../../styles'
import styles from './styles'

const cx = classnames.bind({...globalStyles, ...styles})

<Element className={cx('btn', 'class1', 'class-2')} />
```
