### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by pragya04** [JedWatson/classnames#138]
I get this error while installing classnames using npm 5.3.0 

"Cannot read property '0' of undefined"

How can I resolve it?

**Comment by newyork-anthonyng** [comment]
@pragya04 I'm thinking this might be an issue with the latest version of `npm` or `node`. 

I saw this [issue on npm](https://github.com/npm/npm/issues/17858) where people were running into similar issues. Do any of the solutions there fix your issue?

**Comment by pragya04** [comment]
@newyork-anthonyng Downgraded to 5.2.0 and it worked! Thank you!
