### ISSUE TITLE
Undefined computed keys

### ISSUE THREAD

**Issue by cristianfraser** [JedWatson/classnames#141]
Don't know if comment on https://github.com/JedWatson/classnames/issues/96 because it was closed over a year ago.

Like @dcousens said, 'undefined' could perfectly be a CSS class, so it shouldn't be discarded simply because it's `undefined`. BUT, the reason I see for it to be trashed is consistency. 

For example: `classNames(obj.classA, 'classB')` returns `'classB'` if obj.classA is `undefined`. But `classNames({ [obj.classA]: someBool, classB: someBool })` returns `'undefined classB'`. In the end, those two signatures *should* output the same result, but don't.

I know this is more of a problem with how computed keys are generated by the transpiler, but that `undefined` class name really bugs me. I don't know if there's a nice solution for this, somewhere in the middle that won't output an `undefined` className but knows if it has to. But I think that not outputting `undefined` for object arguments would be the better solution.

**Comment by ipanasenko** [comment]
@cristianfraser what if you write like this: `classNames({ [obj.classA]: obj.classA && someBool, classB: someBool })` ?

**Comment by dcousens** [comment]
@cristianfraser you raise an interesting problem,  but I suspect the behaviour is too cemented now that a breaking change would simply be too disruptive.
