### ISSUE TITLE
I do not understand the use of this project

### ISSUE THREAD

**Issue by andreGarvin** [JedWatson/classnames#142]
I see what I can be used for but it does not understand why you can not just use a tourney statement switch. the react example sense but not really

**Comment by newyork-anthonyng** [comment]
@andreGarvin Do you mean a ternary statement?

This library is just a utility for working with `classNames` in React. For simple cases, you may not need it.

**Comment by andreGarvin** [comment]
okay, I was trying to understand what the project was about and an I was checking it out my code base at work was trying to see if I could contribute to the project

**Comment by newyork-anthonyng** [comment]
@andreGarvin Cool. Do you have any other questions about this project? If not, could you close the issue?

Thanks!
