### ISSUE TITLE
combination of string + value doesn't work

### ISSUE THREAD

**Issue by paddotk** [JedWatson/classnames#143]
Let's say I want to add a classname such as (second one)
```
var class_names = classNames({
  "myclass": true,
  "person"+some_var: true
});
```

then the page throws an error (`unexpected token`).
I tried encapsuling the statement with (parentheses) or {braces} but that doesn't do the trick either.
Is it possible to use a combination of a string and a var? If not, could support for this be added?

Thanks

**Comment by newyork-anthonyng** [comment]
@paddotk 
Is something like this what you're looking for?
https://codepen.io/anon/pen/LOEooZ

I think square brackets is what you need.

**Comment by paddotk** [comment]
@newyork-anthonyng Yes! Perfect, thanks!
