### ISSUE TITLE
Toggle class with Boolean value

### ISSUE THREAD

**Issue by gomo** [JedWatson/classnames#144]
HI! Thank you for awesome function.

If I want output `<div class="true">` when a value is true, otherwise `<div class="flase">`, I write like below.

```js
<div classNames="{classNames({'true': value, 'false': !value})}">...
```

Any idea to write this a bit shorter? 

How about like the below?

```js
<div classNames="{classNames({'true|false': value})}">...
```

What do you think?

**Comment by newyork-anthonyng** [comment]
`classNames` also accepts a `string` value as an argument.

You could use a ternary expression like so:
```js
classNames(value ? "truthyClass" : "falseyClass")
```

**Comment by gomo** [comment]
Thank you for your quick answer.

That's right! :relaxed:
