### ISSUE TITLE
[Feature Request] Classname OR

### ISSUE THREAD

**Issue by IamJoseph** [JedWatson/classnames#149]
Sometimes the logic to determine whether or not a component exists can get complicated. It'd be nice to have a syntax like 
```
classnames({
"className1"|"className2": someFunction
}) 
```

**Comment by newyork-anthonyng** [comment]
@IamJoseph Could you provide a specific use case where the `OR` would be helpful?

The `OR` syntax that you have in your code snippet would be a syntax error. I think this functionality can already be done inside the `classnames` library, like so:
```js
var result = someFunction(); // returns "className1" or "className2"
classnames(result); // returns the className returned by "someFunction"
```

**Comment by WunderBart** [comment]
@IamJoseph wouldn't this be what you're looking for?

```javascript
classNames({
  [className1 || className2]: someFunction
})

**Comment by IamJoseph** [comment]
@WunderBart Yes, does that work? 
@newyork-anthonyng Sorry for the late response/clarification. I was speaking about computed properties. Although now I forget the use case I had in mind 😅

**Comment by newyork-anthonyng** [comment]
@IamJoseph No problem. 

The suggestion that @WunderBart should work. I pasted a code snippet on `repl.it`.

https://repl.it/repls/ElderlySillyAndeancat
