### ISSUE TITLE
Error in typescript: Left side of comma operator is unused and has no side effects.

### ISSUE THREAD

**Issue by kmvan** [JedWatson/classnames#151]
```javascript
import classnames from 'classnames'
classnames({
    'my-lassname': true
})
```

Then at-load shows: `Left side of comma operator is unused and has no side effects.`

I have no idea to let it works...

**Comment by alfaslash** [comment]
You are using the latest versions of npm packages `classnames` and `@types/classnames`?

Try to change import section:
```javascript
import * as classNames from 'classnames';

classNames({
    'my-lassname': true
});
```

**Comment by mayavera** [comment]
@kmvan could you provide some more details on the issue you're having?

**Comment by say8425** [comment]
maybe this https://github.com/JedWatson/classnames/pull/103 is related

**Comment by kmvan** [comment]
Oh, babel-loader cause this error.
The babel-loader can not set below the Awesome-typescript-loader.
