### ISSUE TITLE
Published module is out of date, missing Typescript compatibility fix

### ISSUE THREAD

**Issue by omegdadi** [JedWatson/classnames#152]
This [line](https://github.com/JedWatson/classnames/blob/master/index.js#L42) in particular is missing from the latest npm version 2.2.5. It would be great to get that change released.

**Comment by ruxiang05** [comment]
Bumping this as I have the same problem

**Comment by mariomc** [comment]
Same issue here. Could we add a version bump please?

**Comment by rcchen** [comment]
This issue can be closed, 2.2.6 got released about a month ago.
