### ISSUE TITLE
Classnames ignore toString() method

### ISSUE THREAD

**Issue by Romms** [JedWatson/classnames#153]
I found very useful to have an ability to pass objects with own `toString()` method to classNames function.

ClassNames makes checking is argument type a string, but doesn't check that it is an object with `toString()` method that returns string different from `"[object Object]"`

This checking can allow to combine a few different methods of generation class names, that are useful for libraries that took className from arguments/properties, and pass to classNames function together with own class names.

**Comment by Romms** [comment]
BTW: As I see, React implicitly call `toString()` when making assignment `className` prop to DOM element. So this feature can keep the same behavior for classNames.

https://github.com/facebook/react/blob/51f1205fb4fd6402b155202263ee12571ca4c3a6/src/renderers/dom/fiber/ReactDOMFiber.js#L58

**Comment by Romms** [comment]
I'm seeing the following
```
class Foo {
  constructor() {
     this.bar = true
  }

  toString() {
    return 'class-name';
  }
}

classNames(new Foo())
// 'bar'
```

```
<div className={classNames(new Foo())}/>
// <div class="bar"/>

<div className={new Foo()}/>
// <div class="class-name"/>
```

But I expected to see 

```
classNames(new Foo())
// 'class-name'
```

**Comment by dcousens** [comment]
See https://github.com/JedWatson/classnames/pull/170
