### ISSUE TITLE
Lazy evaluation on classnames

### ISSUE THREAD

**Issue by farskid** [JedWatson/classnames#154]
Hi,

First of all, thanks for creating such a great utility library. It helps me a lot on my projects.

I ran into a situation described as below that I need some sort of lazy evaluation for my classnames.

consider a case where I have a function that creates classname strings out of an array of objects.

```js
function createClassNameFromObject(array) {
  if (!Array.isArray(array) || !array.length || !array.every(item => !!item.a && !!item.b)) {
    throw Error('Some error');
  }
  return array
      .reduce((classname, item) => {
        return [classname, `${item-a}-${item-b}`].join(" ");
      }, "")
      .trim();
}
```

I want to validate objects in the array and if the object doesn't have the required interface, just throw some error.

if I want to use the `createClassNameFromObject` with `classnames` library, no matter the condition, it will run the function since it's not evaluated lazily.

```jsx
function Component({array}) {
  return <div className={classnames('component', {
    [`${createClassNameFromObject(array)}`]: array.length > 0
  })} />
}
```

In this scenario, when `array` prop is not a valid prop regarding validations in `createClassNameFromObject`, since this will evaluate return value of `createClassNameFromObject`, it will make the code throw.

This can be solved if `classname` library accepted function type as classname value.

something like:

```jsx
function Component({array}) {
  return <div className={classnames('component', {
    [`${() => createClassNameFromObject(array)}`]: array.length > 0
  })} />
}
```

This is the only solution on top of my head right now. if there is a way to solve this issue based on current implementation of the library, please tell me so :)

and btw, if the function solution sounds reasonable, I'd be more than happy to open a PR and contribute.

Thanks!

**Comment by newyork-anthonyng** [comment]
@farskid Would something like this work?

```jsx
function Component({ propA, array }) {
  const className = classnames(
    'component', 
    propA.length > 0 && createClassNameFromObject(array)
  )

  return <div className={className} />
}
```

**Comment by farskid** [comment]
@newyork-anthonyng There was a typo about `propA` in my comment. if I could use classnames as a function and pass truthy and falsey values to it as arguments, Yes!

Do we have it right now?

**Comment by newyork-anthonyng** [comment]
@farskid I created this [CodeSandbox demo](https://codesandbox.io/s/vqmjl6k4vl) that seems to work.

Let me know if I'm missing something 👍

**Comment by farskid** [comment]
@newyork-anthonyng It works! thanks.
