### ISSUE TITLE
Ignore missing classes names on binding

### ISSUE THREAD

**Issue by baribadamshin** [JedWatson/classnames#155]
Hey, there! 

When we use css-modules and try to use the missing classnames, we get the original class name in the result string. In some cases it's not pretty well, i mean like dynamic classnames;

How about implement strict mode for the bind version and deletes such values. It seems that the second argument in bind method will be perfect.

What do you think?

**Comment by mayavera** [comment]
Could you provide some illustrative code examples?

**Comment by dcousens** [comment]
@baribadamshin example needed,  no idea what you mean.
Closing until example provided.
