### ISSUE TITLE
Curiosity: Why "cx" as  "classnames"?

### ISSUE THREAD

**Issue by sandrina-p** [JedWatson/classnames#157]
When using classnames, you use `cx`. Why's that?

```js
let cx = classNames.bind(styles);
```

For me, personally, I would use `cn`... what's the meaning of `cx`?

**Comment by JedWatson** [comment]
Early on, React bundled a classNames-like utility in its addons. But it was limited, so I wrote this instead. When the addons got unbundled from React, the team weren't that interested in maintaining theirs so this became the "official" classNames implementation.

The React utility was called "classSet" which works better as `cx` than `cs`... I think the idea may be that you have `x` classes you are applying?

For a little walk through history, I found [this blog post](https://eric.blog/2015/01/19/dynamically-add-classes-react-classset/) about the original utility, which also uses the `cx` shorthand... it stuck, and has persisted 🙂

**Comment by aaj** [comment]
Good enough for me. `cx` it is!
