### ISSUE TITLE
License info being included twice after Webpack 4 build

### ISSUE THREAD

**Issue by bruffstar** [JedWatson/classnames#163]
Not sure if this is a Webpack issue or something with classnames. The reason I don't think it is Webpack is because, in the bundled file, no other third party scripts are adding the license info twice.

I thought it was maybe because there is license info in ``index.js``, ``bind.js`` & ``dedupe.js``. However, I ruled this out after adding a test change in the copyright text in only ``index.js`` and the change was showing on both license comments in the bundle.

**Webpack:** v4.8.3
**NPM:** v5.6.0
**Node:** v8.1.1

Included below is my Webpack config plus a screen shot of the output.

###### webpack.config.js
```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    mode: 'production',
    devtool: "source-maps",
    entry: "./src/js/index.tsx",
    output: {
        path: __dirname + "/dist",
        filename: "js/bundle.min.js"
    },
    resolve: {
        extensions: [".ts", ".tsx", ".js", ".json"]
    },
    module: {
        rules: [
            {
                test: /\.(ts|tsx)$/,
                use: [
                    {
                        loader: 'ts-loader'
                    }
                ]
            },
            {
                test: /\.scss$/,
                use: ExtractTextPlugin.extract({
                    use: [{
                        loader: 'css-loader',
                    }, {
                        loader: 'sass-loader'
                    }],
                    fallback: 'style-loader'
                })
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin({
            filename: 'css/bundle.min.css',
            allChunks: true,
        })
    ],
    externals: {
        "react": "React",
        "react-dom": "ReactDOM"
    },
};
``` 
###### bundle.min.js
![image](https://user-images.githubusercontent.com/1890098/40147634-c09fa3b2-596a-11e8-8790-234c176b6f6c.png)

**Comment by bruffstar** [comment]
I have made a super simple example here: https://github.com/bruffstar/bug-test

See ``dist/index.js`` for an exmaple output with the duplicate license comment.

**Comment by ssingla2** [comment]
Hi 
I am facing an issue that when I generate bundle.js on my localhost using NODE_ENV=production webpack , I am getting file where it is commented "Copyright (c) 2016 Jed Watson."  but when it runs on dev server it is generated with comments "Copyright (c) 2017 Jed Watson. 

I am not sure why it is generated with different copyrights

**Comment by dcousens** [comment]
This is because `LICENSE.md` is being included,  and for whatever reason @JedWatson decided to put the LICENSE prefix in the [`index.js`](https://github.com/JedWatson/classnames/blob/master/index.js) too... hence,  twice.

I don't think I want to ping @JedWatson the 1000's of times necessary to get him to resolve this...

**Comment by vivcogit** [comment]
@dcousens `LICENSE.md` don't included in this case. It's `terser` includes comment with license from `index.js` twice.
I created [issue](https://github.com/terser-js/terser/issues/328) in terser project.

**Comment by vivcogit** [comment]
This bug fixed in terser. I think this issue can be closed
