### ISSUE TITLE
Cut release of classnames to capture changes since 2.2.5

### ISSUE THREAD

**Issue by rcchen** [JedWatson/classnames#164]
Apologies for posting but it seems that there are a [large number of commits that have made it into master since the last release](https://github.com/JedWatson/classnames/compare/v2.2.5...master) but are not captured in any recent release. Would it be possible to cut a release to capture those changes? I'm particularly interested in https://github.com/JedWatson/classnames/commit/915186aaa510e0c6be6c2cf20788aac474790e27

Thank you!

**Comment by alexlafroscia** [comment]
This should be close-able since `2.2.6` was released a week ago!

**Comment by rcchen** [comment]
Awesome, thank you!
