### ISSUE TITLE
Missing git tag for v2.2.6

### ISSUE THREAD

**Issue by tlhunter** [JedWatson/classnames#171]
The commit is present, however the tag is missing.

**Comment by munepom** [comment]
I'm also wondering 🤔 

As far as reading below, v2.2.6 was released in 2018-06-08 (in master branch ?)
https://github.com/JedWatson/classnames/blob/30bd487050de10a016ed2abfd6e602619d166ddc/HISTORY.md

But master branch is still being updated... 
How about creating v2.2.6 tag from https://github.com/JedWatson/classnames/commit/30bd487050de10a016ed2abfd6e602619d166ddc ??

**Comment by dcousens** [comment]
https://github.com/JedWatson/classnames/releases/tag/v2.2.6
