### ISSUE TITLE
Return empty string instead of undefined

### ISSUE THREAD

**Issue by ron-fugue** [JedWatson/classnames#172]
When I pass an empty css class, the component renders the class with `undefined`. Is there a way to have the component render with an empty string instead of `undefined`?

**Comment by newyork-anthonyng** [comment]
Is this #118 related?

**Comment by ron-fugue** [comment]
Similar, but I'm looking to still pass an empty class through in order to "future proof" the classes. The use case would be that in the future, a designer would be able to come along and add styles to said class, and those changes would go through for that class.

So essentially, I'm aware that passing something like `{  empty-class: false }` would remove the undefined. However, i'd like to be able to pass `{ empty-class: true }` without the `undefined` class appearing so that `empty-class` could be styled in the future.

**Comment by newyork-anthonyng** [comment]
```css
.foo { color: red; }
.future-class {
  /* will be implemented in the future */
}
```

```js
const cx = require("classnames");

const myClass = cx("foo", "future-class"); 
// "foo future-class"
```
The `future-class` class name is added to your component. When your designer comes and adds styling to `future-class`, those changes would go through for that class. Let me know if I'm misunderstanding anything 👍

**Comment by ron-fugue** [comment]
Ah thank you, this works!
