### ISSUE TITLE
Use `Set` objects for dedupe

### ISSUE THREAD

**Issue by tom-sherman** [JedWatson/classnames#173]
Has there been any research done in improving the performance of `dedupe` by utilising a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)?

Sets are said to be faster<sup>[[1]](https://github.com/anvaka/set-vs-object) [[2]](https://stackoverflow.com/questions/39007637/javascript-set-vs-array-performance)</sup> and are more idiomatic when dealing with lists of unique elements.

**Comment by dcousens** [comment]
@tom-sherman give it a go!
Is compatability an issue though?

**Comment by newyork-anthonyng** [comment]
I created a [branch](https://github.com/newyork-anthonyng/classnames/commits/feature/an/use-set) here that uses `Set`. I ran the benchmarks locally on my machine; see below.

```
* local#strings x 3,410,647 ops/sec ±0.82% (95 runs sampled)
*   npm#strings x 3,361,959 ops/sec ±0.31% (103 runs sampled)
* local/dedupe#strings x 768,729 ops/sec ±1.36% (90 runs sampled)
*   npm/dedupe#strings x 1,467,791 ops/sec ±0.23% (100 runs sampled)

> Fastest is local#strings

* local#object x 3,086,011 ops/sec ±0.22% (100 runs sampled)
*   npm#object x 3,078,249 ops/sec ±0.16% (102 runs sampled)
* local/dedupe#object x 1,084,332 ops/sec ±1.12% (99 runs sampled)
*   npm/dedupe#object x 2,091,594 ops/sec ±1.89% (98 runs sampled)

> Fastest is local#object

* local#strings, object x 2,756,612 ops/sec ±1.16% (99 runs sampled)
*   npm#strings, object x 2,641,684 ops/sec ±2.83% (96 runs sampled)
* local/dedupe#strings, object x 745,832 ops/sec ±3.45% (92 runs sampled)
*   npm/dedupe#strings, object x 1,335,123 ops/sec ±3.23% (96 runs sampled)

> Fastest is local#strings, object

* local#mix x 1,908,767 ops/sec ±3.32% (94 runs sampled)
*   npm#mix x 1,829,050 ops/sec ±3.97% (93 runs sampled)
* local/dedupe#mix x 494,316 ops/sec ±2.01% (98 runs sampled)
*   npm/dedupe#mix x 645,432 ops/sec ±0.56% (98 runs sampled)

> Fastest is local#mix

* local#arrays x 757,361 ops/sec ±1.58% (94 runs sampled)
*   npm#arrays x 815,488 ops/sec ±2.90% (98 runs sampled)
* local/dedupe#arrays x 384,666 ops/sec ±3.14% (95 runs sampled)
*   npm/dedupe#arrays x 717,931 ops/sec ±3.92% (96 runs sampled)

> Fastest is npm#arrays
```

It seems like using `Set` is slower in a node environment. 
However, I ran this [test in JSPerf](https://jsperf.com/ang-classnames-using-set/1) and it showed a 50% improvement in a browser environment.

**Comment by tom-sherman** [comment]
Woah, a 2x speedup is pretty major! Should `classnames` support non-modern browsers?

**Comment by dcousens** [comment]
@newyork-anthony,  can you try multiple browsers?

**Comment by newyork-anthonyng** [comment]
See here for updated [jsperf numbers](https://jsperf.com/an-classnames-with-set/1). The original ones are returning a `404`.

**Comment by dcousens** [comment]
See https://github.com/JedWatson/classnames/pull/175
