### ISSUE TITLE
Problem Safari 10

### ISSUE THREAD

**Issue by djadriano** [JedWatson/classnames#176]
Hey everybody,

I'm with a problem in Safari 10, I don't know if is of webpack build or just classNames library.

<img width="1334" alt="screen shot 2018-09-21 at 2 11 32 pm" src="https://user-images.githubusercontent.com/160537/45895800-877be800-bda8-11e8-92e0-a6322b2c4241.png">

Anyone have the same problem?

**Comment by newyork-anthonyng** [comment]
Can you provide a basic project/repository that reproduces this error?

**Comment by iamdey** [comment]
I've a user who has this problem too on safari 11 if the error is the same:

https://twitter.com/charlyplaye/status/1133358421225480193/photo/1

it might be something related to webkit. 

safari 12 ok.

I don't have any mac/safari11 to confirm :s
