### ISSUE TITLE
Typescript definitions are missing from package

### ISSUE THREAD

**Issue by cliedeman** [JedWatson/classnames#178]
bind.d.ts and index.d.ts are not in the npm package. But I don't see anything in the project that should cause them to be excluded.

**Comment by dcousens** [comment]
They haven't been released yet.

**Comment by mradamczyk** [comment]
Is there any chance to release version with types definitions sooner than later?

**Comment by seansfkelley** [comment]
Ping @dcousens what would it take to get a release? There's confusion right now about where type definitions belong, since they haven't been released, which is fragmenting work.

**Comment by dcousens** [comment]
@jedwatson needs to review and merge https://github.com/JedWatson/classnames/pull/177,  then publish.

**Comment by seansfkelley** [comment]
🏓  @JedWatson

The types maintainers keep having to field confused contributors; can you please take a look at #177?

**Comment by ElForastero** [comment]
+1

**Comment by dcousens** [comment]
See #177 ...
