### ISSUE TITLE
Please consider provide a webpack loader for `classnames/bind` (for css module).

### ISSUE THREAD

**Issue by hanzhixing** [JedWatson/classnames#181]
We can reduce codes like this
```js
import className from 'classnames/bind';
import styles from './index.css';

const cx = className.bind(styles);
// ...
console.log(cx('center', 'red', className));
```
to
```js
import styles from './index.css';

console.log(styles('center', 'red', className));
```

I've tried by myself.

[Example](https://github.com/hanzhixing/moduled-css-binding-loader)

The loader can be placed after `style-loader` or `MiniCssExtractPlugin.loader`.

**Comment by hanzhixing** [comment]
I found there are at least two another packages for the similar purpose.

[classnames-loader](https://github.com/itsmepetrov/classnames-loader)
[babel-plugin-classnames](https://github.com/giuseppeg/babel-plugin-classnames)

It will be nice if there is an more-official one.

**Comment by dcousens** [comment]
I think this is out of scope.  Happy to re-open by popular demand.

**Comment by vincerubinetti** [comment]
It would be great to have this so I don't have to import classNames over and over and over. Surprised this hasn't gottten more requests.

https://github.com/giuseppeg/babel-plugin-classnames seems good, but it's old, and these days people tend to use Vite for SPAs (so a Babel plugin would be a pain to set up). Also it doesn't work with TypeScript.

Anyone know of a modern plugin to do this?

**Comment by jonkoops** [comment]
I don't think we're interested in providing this. We'd have to maintain several variations to be able to plug this into various parts of the bundler/compiler ecosystem. More than happy to link any community maintained implementations in the README though.
