### ISSUE TITLE
`undefined` should be returned when no classes are needed

### ISSUE THREAD

**Issue by jakubsadura** [JedWatson/classnames#182]
It's quite common that we do not have any class name to be added to DOM, in such case returning `undefined` would allow having cleaner DOM, without empty `class` attributes.

Example with React's jsx:
```js
const isFoo = false;
const isBar = false;
const classes = classNames({
  'foo': isFoo,
  'bar': isBar,
});

return (<i className={classes}/>);
```

results in:
`<i class=""/>`

while it should be:
`<i/>`

@see https://github.com/facebook/react/issues/1448

**Comment by DiscoNova** [comment]
I may be commenting the obvious on this old PR, but this simply will not work no various cases where classnames is still supposed to do its thing while not introducing unexpected classes to elements.

For example ... ```document.documentElement.classList.add(undefined)``` leads to, you may have guessed it ... ```<html class="undefined">``` - which quite likely isn't what the author of the code intended.

**Comment by dcousens** [comment]
See #183
