### ISSUE TITLE
classnames/bind typings don't restrict key types

### ISSUE THREAD

**Issue by gwillz** [JedWatson/classnames#184]
This is a bit weird to explain, so please bear with me.

Edit: I've just realised this probably belongs in @types/classnames.

In the Typescript definitions, the 'classnames/bind' utility accepts a `Record<string, string>`. When passing in a map of values like this, Typescript can extract a set of keys as a string literal type. Currently this is discarded and when using the 'bound' returned function it will allow any random string through.

Using some generics, we can pass these keys down the chain into the returned function, like so:
```ts
type ClassValue<T extends string> = T | T[] | {[k in T]?: any};
    
export default function bind<T extends string>(styles: Record<T, string>)
    : (...classes: ClassValue<T>[]) => string;
```

This means when using the bound function elsewhere, we can be sure that the strings being passed actually exist in the map:
```ts
const styles = { foo: 'xx_foo', bar: 'yy_bar' };
const cx = cn.bind(styles);

cx('foo', 'bar');  // => 'xx_foo yy_bar'
cx({foo: true, bar: false}); // => 'xx_foo'
cx('foobar'); // => TypeError: 'foobar' does not exist in [...]
cx({foobaz: true}); // => TypeError: 'foobaz' does not exist in [...]
```

I haven't submitted a PR because this is pretty fresh and probably needs some input before it's ready. Like, it doesn't re-use any types from 'index.d.ts' and such, so it's not super portable.

Thoughts?

**Comment by Sultanidze** [comment]
@Rogdham it's a cool feature untill you have bootstrap globally in project, `cx('container')` in markup, and empty `.container` class rule inside module styles (or forgot to add it during building markup)

**Comment by Sultanidze** [comment]
Could anybody say, does exist forked project which `bind.js` doesn`t add global className?
I prefer use global className explicitly inside my module:
```scss
.localClassName {
  composes: globalClassName from global;
}
```

I would like to avoid patching it via `patch-package` inside my project

**Comment by webOS101** [comment]
I ran into something similar.  I created a debug version of `classnames.bind` that warns on non-existent keys.  Perhaps it would be useful to add a debug version of `bind` that could be used outside of production to catch these sorts of errors?

**Comment by gwillz** [comment]
I should probably link the discussion [in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32317) for clarity. The ticket was closed because this kind of restrictive typing prevents the pass-through of global styles.

If there was some way to produce warnings instead, I think that'd be more applicable. But only if there were a way to selectively suppress those warnings - for the global-style use case.

**Comment by webOS101** [comment]
@gwillz Yep, I was just adding my $.02. In my debug, I had a list of acceptable global classnames.  BTW, this ticket still shows as open.

**Comment by dcousens** [comment]
The types are restricted now to the same types that are accepted as arguments (see #229),  closing for now.
