### ISSUE TITLE
classNames.bind is not a function

### ISSUE THREAD

**Issue by sunilsharma2214** [JedWatson/classnames#185]
Getting error while jest testing.
error: - Test suite failed to run
    TypeError: classNames.bind is not a function 

**TestComponent.tsx**
import * as React from 'react';
import * as classNames from 'classnames/bind';
var styles = {
  foo: 'abc',
  bar: 'def',
  baz: 'xyz'
};
const cx = classNames.bind(styles);

interface Props {
  title: string;
}
const TestComponent: React.SFC<Props> = props => {
  return <div className={cx('bar')}>{props.title}</div>;
};
export default TestComponent;
------------------------------------------
**TestComponent.test.tsx**
import * as React from 'react';
import TestComponent from './TestComponent';
import { shallow } from 'enzyme';

describe(__filename, () => {
  const props = {
    title: 'Test title',
  };
  it('converts using shallow', () => {
    shallow(<TestComponent {...props} />);
  });
});
---------------------------
**tsconfig.josn**
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "skipLibCheck": true,
    "baseUrl": "./src",
    "allowSyntheticDefaultImports": true,
  },
  "exclude": [
    "node_modules",
    "es",
    "lib",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}

**Comment by sunilsharma2214** [comment]
Thanks, It works for me, but just wanted to understand why it's been working in my some of the project's?, do we need to adjust something in  tsconfig... Thanks.

**Comment by newyork-anthonyng** [comment]
@sunilsharma2214 Can you create a basic sample repository that shows this working?
