### ISSUE TITLE
How to remove a class by condition?

### ISSUE THREAD

**Issue by ninbert** [JedWatson/classnames#193]
How to remove a class by condition?

                 <input
                    className={classnames("form-control", {
                      "is-invalid": errors.password, "is-valid": password.length>=8
                    })}
                    onChange={e => this.onChange(e)}
                    name="password"
                    type="password"
                  />

I want to delete the "is-invalid" class when "is-valid" active.

**Comment by newyork-anthonyng** [comment]
Would this work?

```js
classnames("form-control", {
  "is-invalid": errors.password,
  "is-valid": password.length >= 8 && errors.password
});
```
