### ISSUE TITLE
Question: is it supported to use `classnames/bind` without calling bind() ?

### ISSUE THREAD

**Issue by uhyo** [JedWatson/classnames#195]
Currently, the export of `classnames/bind` can be used just the same as `classnames`, without calling `bind()`:

```js
import classNames from 'classnames/bind';

classNames('foo', { bar: true }); // => "foo bar"
```

But I couldn't find any document nor test which mentions this behavior.
Also, the current type definition doesn't support this usage.

Is this an officially supported behavior, or something we shouldn't rely on?
If the former is the case, I'm planning to send a PR to DefinityTyped to add support of this.

**Comment by newyork-anthonyng** [comment]
See the example in the `README.md`.

```js
var classNames = require('classnames/bind');

var styles = {
  foo: 'abc',
  bar: 'def',
  baz: 'xyz'
};

var cx = classNames.bind(styles);

var className = cx('foo', ['bar'], { baz: true }); // => "abc def xyz"
```

`Function.prototype.bind` is part of JavaScript, and not specific to `classnames`. [See the MDN documentation for more details.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)

I believe it works as expected. See example below:

```js
const classNames = require("classnames/bind");

console.log(classNames);

const styles = {
  foo: "abc"
};
const cx = classNames.bind(styles);
const result = cx("foo", "bar");  // => "abc bar"
```
It prints out `abc` instead of `foo`, because `foo` was found in the `styles` object. It prints out `bar` because `bar` was not found in the `styles` object.

**Comment by uhyo** [comment]
I know it works. I want to know if I can rely on this undocumented behavior.
In other words, I'm asking whether a change to this behavior would be considered as a breaking change.

I'm asking this because the docs or the source code do not answer my question.
Specifically, on writing types for `classnames`, I don't want to give types to what shouldn't be used.

**Comment by newyork-anthonyng** [comment]
@uhyo Do you think updating the docs with an example like the below would be better?

```js
const classNames = require("classnames/bind");

console.log(classNames);

const styles = {
  foo: "abc"
};
const cx = classNames.bind(styles);
const result = cx("foo", "bar");  // => "abc bar"
```

This isn't undocumented behavior. It uses `Function.prototype.bind`.

**Comment by uhyo** [comment]
I would like an example like this:

```js
const classNames = require("classnames/bind");

console.log(classNames("foo", "bar")); // => "foo bar"

const styles = {
  foo: "abc"
};
const cx = classNames.bind(styles);
const result = cx("foo", "bar");  // => "abc bar"
```

I felt that the use of `Function.prototype.bind` could be just an implementation detail.
The only documented thing about `classnames/bind` is how `classNames.bind` can be used,
which means that, the fact that `classNames.bind` is `Function.prototype.bind` is not something guaranteed by the document.

I'd like that guarantee; otherwise, the actual implementation of `classnames/bind` could be changed without major version bump to something like the following, which would break my code above.

```js
module.exports = {
  bind: function (...styles) {
    // ...
  }
}
```

**Comment by newyork-anthonyng** [comment]
Sidenote: [This test shows the behavior that you found](https://github.com/JedWatson/classnames/blob/master/tests/bind.js#L100-L102).

**Comment by uhyo** [comment]
Ahh... not that line, but [this one](https://github.com/JedWatson/classnames/blob/master/tests/bind.js#L18) is what I was looking for.
I can't believe I missed this whole large block of code. 
I'm sorry for opening this issue.
Thank you @newyork-anthonyng for the discussion.
