### ISSUE TITLE
How to use on Edge browser with AMD global?

### ISSUE THREAD

**Issue by BenRussert** [JedWatson/classnames#202]
The Edge browser does not load this library due to the logic below and the `define` global shipped with the Edge browser:

https://github.com/JedWatson/classnames/blob/5d971e41f3b9c8047b61503952a413f00122b52c/index.js#L44-L47

Basically `define` and `define.amd` work as functions in the Edge environment, but `classNames` is still `undefined` after all this runs. Everything works fine in firefox/chrome. Is there a workaround to make things work in Edge?

**Comment by anvaynk** [comment]
Sure, Edge is shipping with Chromium soon! :-P

**Comment by BenRussert** [comment]
Ha, yeah that will fix it.

Anyway I'll close this because I think it was something in my environment.
