### ISSUE TITLE
Feature request: Option to return list of classes instead of just single string

### ISSUE THREAD

**Issue by mikaello** [JedWatson/classnames#204]
`classnames()` returns a single string. While the DOM API function `<element>.classList.add()` expects a rest parameter, which can be given by either supplying individual arguments `add(a, b, c)` or array spread: `add(...[a, b, c])`.

To use `classnames()` with `classList.add()` you will either have to call `add()` multiple times with a single argument to `classnames()`, or split the result and applying array spread: 
```js
add(...(classnames(a, b, c).split(" ")))
```

Internally `classnames` [joins the array of classnames](https://github.com/JedWatson/classnames/blob/bbf03f73f30a24cb7e6df06be7b672b578647523/index.js#L44) before returning, so the array is there. What do you think about an option to return the array without joining, so those in need of an array does not have to do an unnecessary split?

I guess this could be placed under `classnames/list` or something.

Just wanted to bring up the suggestion in case others face a similar need :-)

(Tried to look through all issues to see if this was suggested before, but couldn't find any).

**Comment by dcousens** [comment]
@mikaello `classnames/list` probably!
But,  maybe it might be out of scope for this package?

**Comment by kWeglinski** [comment]
I know it's there for pretty long time but why don't you just wrap it? Make a helper function in project `splitClassNames = (...params) => ...classnames(...params).split('');` so usage would be `add(splitClassnames(a, b, c)`

**Comment by mikaello** [comment]
> I know it's there for pretty long time but why don't you just wrap it? Make a helper function in project `splitClassNames = (...params) => ...classnames(...params).split('');` so usage would be `add(splitClassnames(a, b, c))`

I don't think you could use the spread syntax in the way you do there. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax):
> Spread syntax allows an iterable such as an array expression or string to be expanded **in places where zero or more arguments (for function calls) or elements (for array literals) are expected**

But even if that would have been allowed, it still will require the result of `classnames(..)` to be unnecessarily splitted (unnecessarily because the string is an array in the lib before [being joined](https://github.com/JedWatson/classnames/blob/bbf03f73f30a24cb7e6df06be7b672b578647523/index.js#L44)).

**Comment by kWeglinski** [comment]
True, you can't spread it like that because return has to have one element. So `splitClassNames = (...params) => classnames(...params).split('');` and then `add(...splitClassnames(a,b,c)` OR `addClassnames = (classList, ...params) => classList.add(...classnames(...params).split(''));` What you're looking here for is micro optimisation, which by rule of thumb is not worth to bother. Especially when we talk about super small datasets like list of classes. 
There's also other way - fork classnames and expose it yourself. This repository seems to be dead, see here: https://github.com/JedWatson/classnames/issues/209

**Comment by dcousens** [comment]
I'm not against this,  but I don't think it will be as simple as only returning the array before the `.join`,  and I don't think you could reasonably support the same parameter types without falling back to `.split` internally.

I'd recommend using `.split` yourself for now.
