### ISSUE TITLE
Not compatible with TypeScript

### ISSUE THREAD

**Issue by theKashey** [JedWatson/classnames#205]
> Long story short - publishing d.ts should fix an issue, with a breaking change (probably it worth to complement the update with a codemod)
```diff
- import * as cx from 'classnames';
+ import cx from 'classnames';
```

***

The current version of classnames is not exposing `default` in a ESM format, as well as `d.ts` has no mention of it. As a result `import * as cx from 'classnames'`, is a correct way to load this module from a TypeScript perspective.
However, if the result code would be compiled down using Babel, and Babel can compile TypeScript this would lead to the runtime exception - `cx is not an object`

The reason is `_interopRequireWildcard` helper, which would convert `classnames` to the `{default: classnames}`, which is yet - not a function.

While webpack is managing "harmony imports" by it's own, and managing in a correct (from TypeScript point of view) way - `import *` == `module.exports`, babel is more ESM modules compatible, and wildcard import is working differently in that case.

Proposal:
- update `classnames` to contain `_esModule` property to make it ESM compatible.
- ideally - expose ESM bundle
- update `d.ts` to contain __only__ default export (breaking change), to resolve this issue.

See https://github.com/babel/babel/pull/10574#issuecomment-544107112 for details.

**Comment by nicolo-ribaudo** [comment]
The `d.ts` file already contains `export default classNames`. Which error does typescript report if you do `import classnames from "classnames"`?

**Comment by theKashey** [comment]
It does not throw error in this case. As well it does not throw error for `import * as classnames` and that was how _historically_ classnames were supposed to be imported, as long as local `d.ts` was updated _just_ a year ago.

As a result - the main problem here is `@types/classnames`, which shall be removed, as long as they are containing the _unsafe_ definitions, and _historically_ are included in many projects.

However, `_esModule` prop still has to be defined.

> For the future googlers: __dont add `@types/classnames`__ %username%

**Comment by doxiaodong** [comment]
the `index.d.ts` was not be published

**Comment by mitsuruog** [comment]
Seems `index.d.ts` is not published.  please add the bellow section to your `package.json`

```
"files": [
  "index.d.ts"
]
```

or the workaround is just to use `@types/classnames` for a while.

**Comment by dcousens** [comment]
Waiting on https://github.com/JedWatson/classnames/pull/177
