### ISSUE TITLE
[QUESTION] Conditional classname inclusion using classnames with CSS Modules

### ISSUE THREAD

**Issue by thedanchez** [JedWatson/classnames#207]
Given the following:

```
import cx from 'classnames'
import styles from './myStyles.module.scss'

type Props = {
  loading: boolean
}

const Button = ({loading}: Props) => (
  <button className={cx(styles.btn, {
    [styles.loading]: loading
  })
)
```

The `classnames` library doesn't seem to add the class even the loading condition is met. How do we handle this case? Or can we not use conditions with CSS/SCSS module class names?

**Comment by newyork-anthonyng** [comment]
This should work. Can you create a `codesandbox` that recreates this problem?

[See this codesandbox for a working example](https://codesandbox.io/s/gracious-neumann-nvv2v).

Sidenote: Probably unrelated, but you're missing a closing tag in your `button`
