### ISSUE TITLE
Support for toString on objects

### ISSUE THREAD

**Issue by knobo** [JedWatson/classnames#208]
If an object has a `toString` method (`.hasOwnProperty("toString")`), then this function should be run before further using the result.

A react library that uses classnames, could then be easier to use for those who uses `bem-cn`.

Since react automatically apply .toString() to the className,  many users of react passes an object to className attribute of react components. If that component is a library that uses classnames, there will be compability issues.

**Comment by dcousens** [comment]
Please comment / express support for https://github.com/JedWatson/classnames/pull/170 instead
