### ISSUE TITLE
TypeScript types are not distributed in published package

### ISSUE THREAD

**Issue by langpavel** [JedWatson/classnames#209]
It's not possible to use `classnames` with typescript because types are not published.

**Comment by iRoachie** [comment]
@dcousens can you cut a release with the types included?

**Comment by ScottyFillups** [comment]
Does `npm install --save-dev @types/classnames` work for you? Worked for me :man_shrugging:

**Comment by iRoachie** [comment]
@ScottyFillups the request is to bundle it with the library. It's already in master https://github.com/JedWatson/classnames/blob/master/index.d.ts, just not pushed to npm

**Comment by ScottyFillups** [comment]
Ah, I see

**Comment by liamross** [comment]
Is this repo dead? This would be a nice to have and would be extremely easy to do in a patch version, not sure why types were included in master 16 months ago and still haven't been published

**Comment by JasonLandbridge** [comment]
Was about to say the same thing

**Comment by electic** [comment]
I think it is dead :(

**Comment by inomdzhon** [comment]
Hi, @JedWatson!

Can you please publish version with `index.d.ts` to npm? 🙏 🙏 🙏

**Comment by LitoMore** [comment]
Any progress?

**Comment by liamross** [comment]
No, but in the meantime there is a up-to-date DefinitelyTyped definition for it.

```sh
# yarn
yarn add -D @types/classnames

# npm
npm install --save-dev @types/classnames
```

**Comment by dcousens** [comment]
See https://github.com/JedWatson/classnames/releases/tag/v2.3.0

**Comment by inomdzhon** [comment]
@dcousens thanks a lot! 🙏
