### ISSUE TITLE
Couldn't run in typescript project

### ISSUE THREAD

**Issue by mac066** [JedWatson/classnames#212]
"typescript": "^3.8.2",
"webpack": "^4.42.1",
"webpack-cli": "^3.3.11",
"awesome-typescript-loader": "^5.2.1"

Child process failed to process the request: TypeError: Cannot read property 'kind' of undefined
    at Object.isEntityNameExpression (/node_modules/typescript/lib/typescript.js:16652:21)
but it run in typescript 3.5.2

**Comment by dcousens** [comment]
@mac066 I don't think I can help you without additional information. 
Maybe if you had a resolution you could post it for others?

I'll close this for now, but don't hesitate to re-open if you still experience this.
