### ISSUE TITLE
classnames error when render string "function fixed() { [native code] }"

### ISSUE THREAD

**Issue by tanobi92** [JedWatson/classnames#214]
I have code: 
`const { menuR = {}, fixed = false } = this.props;
		const { collapsed = false } = menuR;
		const cx = classNames(styles.header, {
			[styles.fixed]: fixed,
			[styles.collapsed]: collapsed,
		})`
I  trying use classnames. But it not work. I use debug F12 browser, variable "cx" return "function fixed() { [native code] }".

How to fix it? Help me, please! 
Thanks!

**Comment by newyork-anthonyng** [comment]
@tanobi92 Can you create a simple example of this bug in CodeSandbox?

**Comment by tanobi92** [comment]
@newyork-anthonyng my CodeSandbox: [![Edit config use less as variables](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blissful-field-pw5vd?fontsize=14&hidenavigation=1&theme=dark)

**Comment by tanobi92** [comment]
My project in local actived craco config, but when I show log styles.header, then it return undefined.

**Comment by newyork-anthonyng** [comment]
```js
import styles from "./App.less";

// ...

const test = classnames(styles.header, {
    [styles.fixed]: true,
    [styles.collapsed]: false
});
```

`styles.fixed` is a function; it should be a string. I'm not too familiar with `craco`, but you should look at `css modules`.

**Comment by tanobi92** [comment]
I followed the intructions antd's documents about craco, but it not worked. I tried to use UmiJS to config it to work. Thanks @newyork-anthonyng.

**Comment by tanobi92** [comment]
@newyork-anthonyng help me config with webpack.

**Comment by newyork-anthonyng** [comment]
@tanobi92 You should open a question on StackOverflow. This isn't a problem with `classnames`.
