### ISSUE TITLE
how to implement the ‘>’  for  CSS DIRECT children

### ISSUE THREAD

**Issue by lemarcgagnon** [JedWatson/classnames#215]
Hello! I want to integrate  this style from Makestyle of MUI

"deck > div": {
    position: "absolute",
    width: "95%",
    height: "80%",
    display: "flex",
    justifyContent: "left",
    alignItems: "center",
    willChange: "transform"
  },
  "deck > div > div": {
    backgroundColor: "white",
    backgroundSize: "auto 85%",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center center",
    width: "45vh",
    maxWidth: "300px",
    height: "85vh",
    maxHeight: "570px",
    willChange: "transform",
    borderRadius: "10px",
    boxShadow: "0 12.5px 60px -10px rgba(50, 50, 73, 0.171)"
  }

MY QUESTION...
How do I write this in my <Grid classNames={} >

classNames={classes.deck}

to target elements which are DIRECT children of a particular element.

in Karousel.js in [https://codesandbox.io/s/carousel-marc-4-rr2qv?file=/src/Karousel.js:2266-2291]

Thanks,

Marc

**Comment by newyork-anthonyng** [comment]
You should look at the documentation for `makeStyles`; this question isn't related to `classnames`.

One suggestion is to refactor your CSS and HTML to look like this:
```css
deckInner: {
  position: "absolute",
  /* ... */
}

deckInnerInner: {
  backgroundColor: "white",
  /* ... */
}
```

```html
<div className="deck">
  <div className="deckInner">
    <div className="deckInnerInner"></div>
  </div>
</div>
```
