### ISSUE TITLE
Support arguments array

### ISSUE THREAD

**Issue by mihhail-lapushkin** [JedWatson/classnames#22]
Would be nice if it could expand `arguments` array as well.

**Comment by longlho** [comment]
hmm can u give an example?

**Comment by mihhail-lapushkin** [comment]
Well. Something like:
```js
myAwesomeMethodThatReceivesClassNamesAsVarArgs: function() {
  classNames(arguments, { foo: true, bar: false })
}
```

**Comment by longlho** [comment]
hmm `toString.call(arguments) === '[object Object]'` so we'll have to `[].slice.call(arguments)`, which you can do on your side too, so 
```js
myAwesomeMethodThatReceivesClassNamesAsVarArgs: function() {
  return classNames([].slice.call(arguments).concat({ foo: true, bar: false }));
}
```

**Comment by mihhail-lapushkin** [comment]
That's the point. Why can't it be in the library? It just adds ugliness to my code.

**Comment by longlho** [comment]
performance overhead and not everybody uses it

**Comment by mihhail-lapushkin** [comment]
``arg.length !== undefined`` would kill all the performance?

```
} else if ('object' === typeof arg) {
			if (arg.length !== undefined) {
			   // assume it's arguments
			}

			for (var key in arg) {
```

**Comment by mihhail-lapushkin** [comment]
Okay. Maybe you're right.
It can be an object with `length` also.
Might require some fiddling.
Let's close it then.
