### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by mogzol** [JedWatson/classnames#221]
Pull request #170 was merged in March, and it contains a fix that would be very useful for my codebase, but the version of this package has never been incremented, so I can't use those changes. Could the package version please be incremented and pushed to npm so we can use the new changes?

**Comment by michielmetcake** [comment]
@JedWatson maybe you could add some persons to this repository to maintain it?

**Comment by stefanoruth** [comment]
Would love to get a new release on this repo.

**Comment by steveoh** [comment]
`npm install --save clsx` :trollface:

**Comment by Semigradsky** [comment]
Friendly ping @JedWatson

**Comment by xiaoxiangmoe** [comment]
Friendly ping @JedWatson

**Comment by JedWatson** [comment]
Sorry for the delay here, @dcousens has been helping and recently shipped a new version with the merged changes.

**Comment by JedWatson** [comment]
Wait, no sorry - I just checked and it looks like the npm publish hasn't happened yet (although the blocking PRs have been merged)

I'll check that out first thing tomorrow and make sure we actually do publish it
