### ISSUE TITLE
Add jscodeshift codemod to README

### ISSUE THREAD

**Issue by jayu** [JedWatson/classnames#224]
Hey, I created a [jscodeshift](https://github.com/facebook/jscodeshift) codemod for migration from template literal based class names concatenation to this library. 
It would be awesome to link it somewhere in the readme, then potentially more people could use it. 
I'm happy to open a PR if you don't mind

Here is the codemod https://github.com/jayu/template-literal-classnames-codemod

**Comment by dcousens** [comment]
Thanks for sharing the interesting library @jayu - in this instance I'm opting not to add the library to README to reduce a maintenance burden of keeping that list relevant and up-to-date.
