### ISSUE TITLE
Computed property type

### ISSUE THREAD

**Issue by KevinBurton** [JedWatson/classnames#225]
I have the following in a TypeScript file:

```
  const cardClasses = classNames({
    [classes.card]: true,
    [classes.cardPlain]: plain,
    [classes.cardProfile]: profile,
    [classes.cardChart]: chart,
    [className]: className !== undefined
  });
```
This gives me

```
Type error: A computed property name must be of type 'string', 'number', 'symbol', or 'any'. 

  25 |     [classes.cardProfile]: profile,
  26 |     [classes.cardChart]: chart,
> 27 |     [className]: className !== undefined
     |     ^
  28 |   });
```

I don't know enough about TypeScript to see what I am doing wrong, Ideas?

**Comment by borisowsky** [comment]
Without context, it's hard to understand what's going on in your code, but try this out:
```js
const cardClasses = classNames(className, {
  [classes.card]: true,
  [classes.cardPlain]: plain,
  [classes.cardProfile]: profile,
  [classes.cardChart]: chart
});
```

**Comment by ekim088** [comment]
> Without context, it's hard to understand what's going on in your code, but try this out:
> 
> ```js
> const cardClasses = classNames(className, {
>   [classes.card]: true,
>   [classes.cardPlain]: plain,
>   [classes.cardProfile]: profile,
>   [classes.cardChart]: chart
> });
> ```

This should work. Since `className` is possibly undefined TS won't let you use it as a key without casting or converting it.

**Comment by GLObus303** [comment]
I am getting the same from scss modules and I cant get past it.

<img width="693" alt="CleanShot 2023-10-14 at 12 50 36@2x" src="https://github.com/JedWatson/classnames/assets/12488648/a7aef05c-1d00-41d7-b74c-73a10b9fe2f3">

Any solutions?
