### ISSUE TITLE
This expression is not callable. Type 'typeof import (./path) has no call signatures.

### ISSUE THREAD

**Issue by fazeelzama20** [JedWatson/classnames#233]
The version which published today 3 hours ago (01/04/2021) having some breaking changes. The project was working fine before the last update. Currently, I am using the version "@types/classnames": "^2.2.0",  "classnames": "^2.2.6".
While running the build I am getting the below error
"This expression is not callable. Type 'typeof' import (./path) has no call signatures."

**Comment by OlehStepaniuk** [comment]
Got the same error, just changed import * classNames from 'classnames' -> import classNames from 'classnames' and now works fine.

**Comment by rouwe111** [comment]
I've got the same problem. I am using `import classNames from 'classnames/dedupe';`.

```
This expression is not callable. Type 'typeof import("/node_modules/classnames/dedupe")' has no call signatures.
```

**Comment by dcousens** [comment]
`import classNames from 'classnames'` is what you want.

As for `dedupe`, it is missing a default export, I will fix that bug.
