### ISSUE TITLE
Objects without index signature cannot be passed as an argument (TypeScript)

### ISSUE THREAD

**Issue by dkaraush** [JedWatson/classnames#235]
Today got an error while building my project. Digging deeper I saw a commit: https://github.com/JedWatson/classnames/commit/6c684f8b2a2ca2e764eac0dd35c5c7af19c2b7f5

Basically it breaks two features of the library:
1) sending objects
There is new `Mapping` which strictly has an index signature (`{ [key: string]: Value };`) and this can be incompatible with objects that don't have such signature. For example:
```
const Component = ({ myProp, ...otherProps }: {
    myProp: any,
    flag1: boolean,
    flag2: boolean,
    flag3: boolean
}) => {
    cx(otherProps);
    return null;
}
```
would throw an error
```
Argument of type '{ flag1: boolean; flag2: boolean; flag3: boolean; }' is not assignable to parameter of type 'Argument'.
  Type '{ flag1: boolean; flag2: boolean; flag3: boolean; }' is not assignable to type 'Mapping'.
    Index signature is missing in type '{ flag1: boolean; flag2: boolean; flag3: boolean; }'
```

2) sending any value in objects
I thought it was a feature to send anything that would be `true` after casting it to `boolean`, so I have been sending functions, arrays and objects. Real example: I have a component with `onClick` callback and a logic that if there is no callback, then component is not clickable and it will look different. So I just sent `{ clickable: onClick }`
I know it can be bad, but it worked before! and now it doesn't.
And this wasn't a major version update so npm wouldn't take a newer version.

classnames v2.3.0
TypeScript v4.2.3

**Comment by dcousens** [comment]
@dkaraush please try `classnames@2.3.1`,  this should have been resolved (credit to @remcohaszing for the timely PR)

**Comment by dkaraush** [comment]
Tested and it works, thanks to @remcohaszing!
Closing an issue.
