### ISSUE TITLE
Typescript <3.7 is not supported

### ISSUE THREAD

**Issue by flowven** [JedWatson/classnames#236]

**Comment by flowven** [comment]
![image](https://user-images.githubusercontent.com/11953505/113396542-4380e980-93ce-11eb-9672-06745ad69402.png)

**Comment by dcousens** [comment]
@flowven this raises an excellent question,  what is the minimum version of typescript that we want to support?

**Comment by Semigradsky** [comment]
Typescript v3.6 Release date - August 2019.
`DefinitelyTyped` support 2 years old versions. What's about `classnames`?

**Comment by remcohaszing** [comment]
If this is desired, I can setup tests for multiple TypeScript versions using dtslint, which is what DefinitelyTyped uses for testing multiple TypeScript versions as well.

**Comment by dcousens** [comment]
@flowven any reason for close?

**Comment by flowven** [comment]
@dcousens I have updated typescript

**Comment by dcousens** [comment]
I think a 2 year LTS-like support schedule is the path forward,  but we only recently added these types, thereby we aren't actually in a maintenance period for them?
Without a show of support for <3.7,  I'm happy to leave this as is.

**Comment by coadan** [comment]
Isn't it possible to rewrite it to be backwards compatible?

```
export type Value = string | number | boolean | undefined | null;
export type Mapping = { [key: string]: any };
interface Args extends Array<Value | Mapping>{}
export type Argument = Value | Mapping | Args;

export default function classNames(...args: Argument[]): string;
```

I believe this should be functionally the same as the self referencing one.

**Comment by dcousens** [comment]
@coadan open a pull request? :smile:

**Comment by coadan** [comment]
@dcousens  https://github.com/JedWatson/classnames/pull/248
