### ISSUE TITLE
Convert to ESM only

### ISSUE THREAD

**Issue by remcohaszing** [JedWatson/classnames#238]
On 2021-04-30, 25 days from now, NodeJS 10 will reach end of life. From that point all NodeJS environments will support ESM. Of course module bundlers already support this.

There are two older pull requests to achieve this. Both are trying to keep backwards compatibility

- #150
- #194

I think it’s time to drop support for alternative module systems and bower, meaning no new devdependencies are needed.

Bower users can depend on specific git tags. It the `master` branch should keep working for Bower users, perhaps a new `main` branch should be created for further development, so the `master` branch can stay untouched indefinitely.

I expect this to get some backlash at first from people who don’t like breaking changes, but this is what major releases are for in semver.

**Comment by JedWatson** [comment]
This is really close to something @dcousens and I were talking about just last week 👍 

I am not sure that having `master` and `main` both in the project will make it easier for most people but it's definitely an interesting idea!

But really at this point I think a new major version that's future-facing would be great.

**Comment by remcohaszing** [comment]
> I am not sure that having master and main both in the project will make it easier for most people but it's definitely an interesting idea!

I wouldn’t reommend it though. This was purely an idea not to break bower users depending on the `master` branch, which I think is a bad idea anyway.

**Comment by jonkoops** [comment]
@remcohaszing I believe that Node 12 (which is an LTS version) does not support this syntax unless you explicitly pass the `--experimental-module` flag when starting Node. Perhaps this is not so for packages, but I cannot find any documentation that indicates this.

**Comment by remcohaszing** [comment]
From https://nodejs.org/en/blog/release/v12.22.0/

> #### ES Modules
> ES Modules are now considered stable.
>
> Contributed by Guy Bedford [#35781](https://github.com/nodejs/node/pull/35781)

**Comment by jonkoops** [comment]
Nice, that's great. Glad the Node team decided to flip this one on in a minor release.

**Comment by jonkoops** [comment]
I've forked the repo and played around a bit to see what the impact is of switching to ES modules (see #243).

**Comment by jonkoops** [comment]
I believe this issue can be closed as this has been resolved on the `next` branch

**Comment by otakustay** [comment]
Do we have an estimate on the release time of `next` branch? For now tools like `vite` are getting more and more popular, they heavily rely on ESM packages.

**Comment by jonkoops** [comment]
I think it might be time to add a tracking issue to see what needs to be resolved before it is released. I don't think there is much to do besides to use more modern ES syntax, which can also be done at a later point.

**Comment by ptgamr** [comment]
+1 to this issue, currently get this issue bundling with Vite

```
caught SyntaxError: The requested module '/@fs/...../node_modules/classnames/index.js?v=5eae925e' does not provide an export named 'default'
```

**Comment by jonkoops** [comment]
@dcousens @JedWatson how would you feel about merging `next` into `main`? I can volunteer time if there are issues to be resolved for the next major.

**Comment by FrSenpai** [comment]
> +1 to this issue, currently get this issue bundling with Vite
> 
> ```
> caught SyntaxError: The requested module '/@fs/...../node_modules/classnames/index.js?v=5eae925e'
> does not provide an export named 'default'
> ```

Same problem here, on vite too... Any ideas to fix it ?

**Comment by jonkoops** [comment]
Re-opening this for administrative reasons, we have yet to merge this work into `main`.
