### ISSUE TITLE
Typescript is not working properly

### ISSUE THREAD

**Issue by Utkarshbhimte** [JedWatson/classnames#246]
```
Could not find a declaration file for module 'classnames'. '/Users/utkarsh/Documents/code/noggin-v2/node_modules/classnames/index.js' implicitly has an 'any' type.
```
This is the error I am getting 

When I went to the node_modules, there is no index.d.ts file 
![image](https://user-images.githubusercontent.com/13379773/116132607-5cd63680-a6eb-11eb-8818-9a3ace229353.png)

What is happening here? All other libraries are working fine.

**Comment by dcousens** [comment]
@Utkarshbhimte what version of classnames are you using?

**Comment by bmakan** [comment]
I had the same issue. Even after running `npm i --save-dev @types/classnames` the ts couldn't find the declaration files. I upgraded to `v2.3.1` and the issue's gone. (Was on `v2.2.6` previously.)

**Comment by Utkarshbhimte** [comment]
@dcousens `2.2.6`

**Comment by dcousens** [comment]
Typescript types were only added to this repository in [v2.3.0](https://github.com/JedWatson/classnames/blob/8d6f4f1c84da2402b6765be8d7b7d0d6b1dc835c/HISTORY.md#v230--2021-04-01)

**Comment by WoodyWoodsta** [comment]
I think a proper changelog would help with these types of questions.
