### ISSUE TITLE
Test the Typescript types

### ISSUE THREAD

**Issue by dcousens** [JedWatson/classnames#249]
https://github.com/JedWatson/classnames/pull/248 has brought to my attention that the types, as is, are seemingly equivalent to `classNames(...args: any[]): string`.

It'd be nice to have some tests to verify that _isn't_ the case, otherwise, we could probably simplify the definitions...

**Comment by dcousens** [comment]
@remcohaszing you mentioned `dtslint` might be useful here, did you have anything particular in mind before I search this space?

**Comment by dcousens** [comment]
@coadan if this isn't something we can turn around in a few days, I'll publish your changes as is :+1:

**Comment by remcohaszing** [comment]
syntax-tree/unist-util-remove#3 is just a random example of what it could look like.

Basically:

- Add `tslint.json`
- Add `tsconfig.json`
- Add `classnames-test.ts`, which contains the actual tests
- Update CI to run `dtslint`.

This will assert the types work for various TypeScript versions. This is the same tool that’s used by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

I’ll gladly create a PR for this later today if this is desired.

**Comment by dcousens** [comment]
@remcohaszing if you'd like to do the PR, that'd be highly appreciated!  The steps + link provided is amazing on their own though and I'm happy follow up if you run out of time. :+1:
