### ISSUE TITLE
Replace Object.prototype.toString.call with Array.isArray

### ISSUE THREAD

**Issue by klimashkin** [JedWatson/classnames#25]
https://jsperf.com/array-isarray-vs-instanceof-array/5

**Comment by dcousens** [comment]
@klimashkin you could also just do

`object !== null && object.constructor === Array`

Which is 400% faster again.  See https://jsperf.com/array-isarray-vs-instanceof-array/12

**Comment by klimashkin** [comment]
Yep, but it have a point if you check array.
If it is not array (and commonly we have no array as argument, more common are objects and booleans) faster to use Array.isArray

**Comment by dcousens** [comment]
You're right,  however if we just moved the `else if (check if Array` branch to last, then it would be taking advantage of the fact that all other options failed, so it the assumption that is an `Array` is therefore more likely.

**Comment by klimashkin** [comment]
But if we'll make array check the last, we should move check for object above, ie replace ```'object' === typeof arg``` with Object.prototype.toString.call(arg) === '[object Object]' which is slower

**Comment by dcousens** [comment]
I'll look into it.  Haven't had time to check over it thoroughly yet.

**Comment by stuartsan** [comment]
Mentioned in #24 but also relevant here:

The issue with using instanceof Arrray or thing.constructor === Array is that it may fail when multiple frames are in use, because different frames' constructors have different identities, so frame 1's Array !== frame 2's Array.

**Comment by dcousens** [comment]
Merged in https://github.com/JedWatson/classnames/pull/24
