### ISSUE TITLE
add support for hyperscript

### ISSUE THREAD

**Issue by lesar** [JedWatson/classnames#254]
at this [row](https://github.com/JedWatson/classnames/blob/1594fd7637fa30f538f262894e9f0d3ba4067992/index.js#L44) if we can make join on classes parameterized we can use on hyperscript too.  
some like this:  
```javascript
var classSeparator = ' '

export function cfg(opt) {
  if (opt && opt.classSeparator) {
    classSeparator = opt.classseparator
  }
}
export classNames() {
//........
return classes.join(classSeparator);
//........
}
// ....
```
In this manner a user can import cfg on first main js file and do:  
```javascript
cfg({ classSeparator: '.' })
// ......
classNames({ pio: true, bau: true })
// to get
// 'pio.bau'
```
this can be use in hypescript:  
```javascript
h('div.'+classNames({pio: true, bau:true}), text)
```

what do you think about?

**Comment by dcousens** [comment]
I think hyperscript might be out of scope for this library
