### ISSUE TITLE
Do not return numbers

### ISSUE THREAD

**Issue by amandaol** [JedWatson/classnames#256]
A class name can not be a number/digit: https://www.w3.org/TR/CSS2/syndata.html#characters

While a class name can contain a digit, it can not be lead with a digit which means, among other things, the class name can not be only a number/digit.

Line https://github.com/JedWatson/classnames/blob/master/index.js#L22 specifically supports a use case (returning a digit/number) which will never work. 

I think it would be best to not support cases which literally do not work. 

Am I missing something obvious? Thank you!

(It is true that the user experience will not necessarily be broken by a number being passed through this function. But if the developer using this function does not know that browsers do not read class names which are only numbers/digits, then the styles he has associated with this number will not be applied. In that sense, part of the users experience will be broken.)

**Comment by dcousens** [comment]
Hi @amandaol ,  we recently discussed this in https://github.com/JedWatson/classnames/issues/239,  please follow up any questions/comments there :+1:
