### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by Mihai-github** [JedWatson/classnames#262]
Hi,

    Is Typescript support available for classnames package or not yet? I'm asking because even if I install @types/classnames as a devDependencies I'm still getting the error that is not installed and give me the recommendation to install it.
    Has anyone solved this problem and how (please) or still persists?

Thanks

**Comment by jonkoops** [comment]
@Mihai-github Yes, the package includes type definitions by default, you should not have to install `@types/classnames`.

If you want to know if a package has types included you can see this on the NPM page of that package. For example, if you visit the page for [`classnames`](https://www.npmjs.com/package/classnames) you'll see this next to the title.

![A tooltip showing types are included for a package](https://user-images.githubusercontent.com/695720/129768797-2751abd5-b201-49ea-96e3-6f64159e630b.png)

**Comment by Mihai-github** [comment]
> @Mihai-github Yes, the package includes type definitions by default, you should not have to install `@types/classnames`.
> 
> If you want to know if a package has types included you can see this on the NPM page of that package. For example, if you visit the page for [`classnames`](https://www.npmjs.com/package/classnames) you'll see this next to the title.
> 
> ![A tooltip showing types are included for a package](https://user-images.githubusercontent.com/695720/129768797-2751abd5-b201-49ea-96e3-6f64159e630b.png)
> 
> 
> 
But... have you any idea why in my project and say that i have not installed it..
My guess is because i added in ts.config the option noimplicitany and it does not know the fact that this package has already inside of it types. 
This is my guess and i think i have to tell him manually.

**Comment by bezreyhan** [comment]
I also just ran into this issue. It looks like the TS definitions were not being included. I just downloaded the latests version of `classnames` and it seems that the issue has been resolved.

`npm install classnames@latest`

**Comment by Mihai-github** [comment]
> I also just ran into this issue. It looks like the TS definitions were not being included. I just downloaded the latests version of `classnames` and it seems that the issue has been resolved.
> 
> run: `npm install classnames@latest`

Thanks bro, it worked :)
