### ISSUE TITLE
Name of variable with empty object used as class name

### ISSUE THREAD

**Issue by strarsis** [JedWatson/classnames#267]
When passing in an empty JavaScript object (`let something = {}`) the variable name will be used as a class name (`something`) instead just being ignored as it doesn't contain class names to be toggled.

**Comment by dcousens** [comment]
@strarsis `classnames` is not recursive,  however,  we do iterate the arguments.
When evaluating an object,  [as per the README](https://github.com/JedWatson/classnames#usage):

> If the value associated with a given key is falsy, that key won't be included in the output.

We do not recursively dive into that object in any way.

For example

```js
const classnames = require('./')

console.log(classnames({ foo: {} }))
// foo

console.log(classnames({ foo: { hello: true } }))
// foo

console.log(classnames({ foo: { hello: true } }, { bar: {} }))
// foo bar
```
