### ISSUE TITLE
get [object Object] in sandbox

### ISSUE THREAD

**Issue by FanShiDe** [JedWatson/classnames#278]
I'm running code in sandbox provided by [vm2](https://github.com/patriksimek/vm2/blob/c5fb7d939385880f9d0d05f0180f8cf3c8f4c732/README.md)
```js
const classnames = require('classnames')

function test() {
  var a = { name: true };
  const result = classnames(a)

  console.log('result', result)
}

test();
```

Because of vm2 provide proteced object, so the code `arg.toString === Object.prototype.toString` will get false
https://github.com/JedWatson/classnames/blob/f2379c3d1eae8c9d6527279bc6a0630a2e78b051/index.js#L32

I think that should to be changed to `arg.hasOwnProperty('toString') && typeof arg.toString === 'function'`, so that compatible with various running environments

**Comment by LassazVegaz** [comment]
I am working on this

**Comment by dcousens** [comment]
Fixed in https://github.com/JedWatson/classnames/pull/281
