### ISSUE TITLE
Please publish a new version

### ISSUE THREAD

**Issue by paleite** [JedWatson/classnames#279]
The currently published version is 15 months old, but there have been some typescript-changes around 12 months ago (index.d.ts) which have yet to be published. Please publish them in a new version.

**Comment by MyGuySi** [comment]
Glad it's not just me, would have spent hours debugging this 🙏

**Comment by orosznyet** [comment]
Hmm, then I might go with https://github.com/lukeed/clsx

**Comment by dcousens** [comment]
A new version should be released later today

**Comment by dcousens** [comment]
Published https://www.npmjs.com/package/classnames/v/2.3.2

**Comment by kivervinicius** [comment]
@dcousens Hello, the changes published in 2.3.2 broke most imports with ts

**Comment by dcousens** [comment]
@kivervinicius could you open a new issue with an example we can use to reproduce the issue?

**Comment by bytemain** [comment]
> @dcousens Hello, the changes published in 2.3.2 broke most imports with ts. Example:
> 
> ```ts
> src/CheckBox/CheckBox.tsx:95:41 - error TS2345: Argument of type '["omg-checkbox", className, { "omg-checkbox-white": boolean; "report-field": boolean | undefined; "is-flex": unknown; "use-label-space": boolean; "not-animated": boolean; "omg-checkbox-small": boolean; }]' is not assignable to parameter of type 'ArgumentArray'.
>   Type 'className | { "omg-checkbox-white": boolean; "report-field": boolean | undefined; "is-flex": unknown; "use-label-space": boolean; "not-animated": boolean; "omg-checkbox-small": boolean; }' is not assignable to type 'Argument'.
>     Type 'Object' is not assignable to type 'Argument'.
>       The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
>         Type 'Object' is not assignable to type 'Mapping'.
>           The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
>             Index signature for type 'string' is missing in type 'Object'.
> ```
> 
> With 2.3.1 it doesn't happen

Meet the same problem

**Comment by dcousens** [comment]
@bytemain could you open a new issue with an example we can use to reproduce the problem?
