### ISSUE TITLE
bind method doesnt provide intellisense for css modules

### ISSUE THREAD

**Issue by leadq** [JedWatson/classnames#280]
I am using scss.module in my project and when I use classnames library, I bind the style and use like below

```
import classnames from 'classnames/bind';
import style from './style.module.scss';

const cx = classnames.bind(style)

const Component = () =>{
..
..
  return (
    <div className={cx('container', { foo1: true, foo2: false })}>  </div>
  )
}
```

container , foo1, and foo2 are classes in my style module file.

I think it should suggest the classes which are exist in style file but it does not. For example, when I write container or foo1, it doesn't recognize and suggest

Note: I am using react v17, TS v4 and css modules extension

Am I missing something ?

**Comment by dcousens** [comment]
@leadq can you still reproduce this with the latest release?
