### ISSUE TITLE
Return 'void' instead of 'undefined'

### ISSUE THREAD

**Issue by geoffmunn** [JedWatson/classnames#289]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `classnames@2.3.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/classnames/bind.d.ts b/node_modules/classnames/bind.d.ts
index 0cdd158..fe40e2a 100644
--- a/node_modules/classnames/bind.d.ts
+++ b/node_modules/classnames/bind.d.ts
@@ -4,6 +4,6 @@ declare namespace classNames {
 	type Binding = Record<string, string>;
 }
 
-declare function classNames(this: classNames.Binding | undefined, ...args: ArgumentArray): string;
+declare function classNames(this: classNames.Binding | void, ...args: ArgumentArray): string;
 
 export = classNames;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dcousens** [comment]
@geoffmunn out of interest, how did this impact thus that you needed to patch the package?

**Comment by geoffmunn** [comment]
> 

I get this message:
```
TS2684: The 'this' context of type 'void' is not assignable to method's 'this' of type 'Binding | undefined'.
    20 |     <nav>
    21 |       <header className={styles.header}>
  > 22 |         <NavLink to="/" className={classNames(styles.item, styles.logo)}>
       |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    23 |           <strong>Terra</strong> Station
    24 |         </NavLink>
    25 |

```
when using it like this:

```
import { PropsWithChildren } from "react"
import classNames from "classnames/bind"
import { Color } from "types/components"
import { InlineFlex } from "../layout"
import styles from "./Tag.module.scss"

const cx = classNames.bind(styles)

interface Props {
  color: Color
  small?: boolean
}

const Tag = ({ color, small, children }: PropsWithChildren<Props>) => {
  const className = classNames(styles.tag, `bg-${color}`, cx({ small }))
  return <InlineFlex className={className}>{children}</InlineFlex>
}

export default Tag
```

The file in question can be found here:
https://github.com/terra-money/station-extension/blob/main/src/components/display/Tag.tsx

I am upgrading this to the latest npm modules and this was a very common failure. Changing the return type fixed the problem, but I am happy to take any other solution you can think of.

**Comment by dcousens** [comment]
@geoffmunn you are using `classNames from "classnames/bind"` bind within `Tag`.
Maybe you wanted `cx` or the non-bind variant?
