### ISSUE TITLE
Need support to append string in a class 

### ISSUE THREAD

**Issue by Sabih-KL** [JedWatson/classnames#291]
class : "lty-fs-"
input : 38
output : "lty-fs-38"
How do i achieve this with class names ?

**Comment by saad277** [comment]
also need to know ^^

**Comment by fromaline** [comment]
@Sabih-KL, read [the docs](https://github.com/JedWatson/classnames#dynamic-class-names-with-es2015), classnames have you covered.

```js
import cn from 'classnames';

// 38
const input = getInput();

// lty-fs-38
const classes = cn({ [`lty-fs-${input}`]: true })
```

**Comment by lofayo** [comment]
> @Sabih-KL, read [the docs](https://github.com/JedWatson/classnames#dynamic-class-names-with-es2015), classnames have you covered.
> 
> ```js
> import cn from 'classnames';
> 
> // 38
> const input = getInput();
> 
> // lty-fs-38
> const classes = cn({ [`lty-fs-${input}`]: true })
> ```

You are right! I get it .
