### ISSUE TITLE
Interface types aren't compatible in 2.3.2

### ISSUE THREAD

**Issue by bytemain** [JedWatson/classnames#294]
I meet a typing issue in 2.3.2:

it worked on 2.3.1.

```ts
import classNames from 'classnames';

export interface ValidateType {
  error?: boolean;
}

const result: ValidateType | undefined = {
  error: true
} as ValidateType;

const data = classNames(result);
console.log(`🚀 ~ file: index.ts ~ line 10 ~ data`, data);

```

<img width="1351" alt="CleanShot 2022-11-11 at 19 58 56@2x" src="https://user-images.githubusercontent.com/13938334/201335998-46bacedc-85df-4e7f-8146-3dba5b93af90.png">

```
[{
	"resource": "/private/tmp/artin-QVhj2J/index.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '[ValidateType]' is not assignable to parameter of type 'ArgumentArray'.\n  Type 'ValidateType' is not assignable to type 'Argument'.\n    Type 'ValidateType' is not assignable to type 'Mapping'.\n      Index signature for type 'string' is missing in type 'ValidateType'.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 25,
	"endLineNumber": 11,
	"endColumn": 31
}]
```

**Comment by bytemain** [comment]
remove the question token from `ValidateType` make it worked

**Comment by bytemain** [comment]
```ts
import classNames from 'classnames';

export interface ValidateType {
  error: boolean;
  [key: string]: any;
}

const result: ValidateType = {
  error: true,
};

const data = classNames(result);
console.log(`🚀 ~ file: index.ts ~ line 10 ~ data`, data);

```

this is work.

**Comment by dcousens** [comment]
Issue broken down

```typescript
type Foo = {
  bar: boolean
}

const foo: Foo = { bar: true }
classNames(foo) // ok
```

```typescript
interface Foo {
  bar: boolean
}

const foo: Foo = { bar: true }
classNames(foo) // Argument of type '[Foo]' is not assignable to parameter of type 'ArgumentArray'
```

**Comment by jonkoops** [comment]
@dcousens do we have a solution in the works for this issue? Anything that can be added to the failing test PR to fix this?

**Comment by jonkoops** [comment]
So the reason for this regression is that the type for `Mapping` [was changed](https://github.com/JedWatson/classnames/commit/dec702ac2523157cab7c81da9e35e851ef0e562b#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R13) from `Record<string, any>` to `Record<string, unknown>`. We could revert this to the original, which should resolve the issue, it doesn't really affect the type-safety of our code, or of users in any meaningful way anyways
