### ISSUE TITLE
why not using one build tool for publish the npm package?

### ISSUE THREAD

**Issue by xgqfrms** [JedWatson/classnames#297]
# I didn't found any build scripts in the `pacakge.json` file

https://github.com/JedWatson/classnames/blob/main/package.json#L13-L18

> verified

```sh
$ npm i classnames
# node_modules
```

![image](https://user-images.githubusercontent.com/7291672/204036884-91636315-76de-4d04-82bc-9b2b9cc8c4a3.png)

**Comment by xgqfrms** [comment]
# suggestion

`src/` => `dist.` / `build/`

**Comment by dcousens** [comment]
I think we're pretty happy with the status quo, the investment of time doesn't necessarily have a benefit at this time
