### ISSUE TITLE
Incomplete type signature for classnames/bind

### ISSUE THREAD

**Issue by imamatory** [JedWatson/classnames#299]
Hi! There is a use case for classnames when I use css-modules and need to concatenate names that must be transformed with already transformed ones.
For example:
```ts
import cn from 'classnames/bind';
const cx = cn.bind(styles);
const Compinent = ({ className }) => <span className={cn(cx('text-bold'), className)}
```
Where `className` is a string containing transformed classes.

So now this code contains a type error `The 'this' context of type 'void' is not assignable to method's 'this' of type 'Binding'.`

Is it a valid use case for you? Or maybe it makes sense to add `void` to the type signature of `this` as it was in old versions?

https://github.com/JedWatson/classnames/blob/495e24d98c245f849858998955d3b7442d614e3c/bind.d.ts#L7

**Comment by jonkoops** [comment]
Seems like this is a type-safety issue stemming from the fact that `Function.prototype.bind()` itself is not type-safe, and instead returns `any`. Not quite sure how we would go about fixing that without overwriting the type in this specific instance.

**Comment by jonkoops** [comment]
My mistake, it looks like this is a question about mixing classes, rather than a bug report for the types of `classnames/bind` (which we should also fix seperately). You can pass any additional classes into the bound function, and they will be applied as expected:

```js
import classNames from 'classnames/bind';

const styles = { 'text-bold': 'mapped-class' };
const cx = classNames.bind(styles);
const className = cx('text-bold', 'some-other-class');

console.log(className); // => 'mapped-class some-other-class'
```
