### ISSUE TITLE
Some issues to make this compatible with React addon classSet

### ISSUE THREAD

**Issue by chenglou** [JedWatson/classnames#3]
1. `classnames('a', false)` produces `'a false'` in classSet, but classnames ignores `false`. Passing `null` crashes it. Passing `undefined` gets it ignored. Doesn't matter what the desirable behaviour is; it breaks compatibility with classSet.

2. Bikeshedding: I know this has nothing to do with React, but React uses `className` so it'd be nice if this could be `classNames` camelCased.

3. Empty class names return `undefined` rather than `''`.

**Comment by chenglou** [comment]
I'm totally fine if you keep the current behaviour. I'll link to both https://github.com/petehunt/react-classset and this in the new React classSet readme.

**Comment by chenglou** [comment]
Update: feel free to keep your current behaviour! I made that above repo fully backward compatible so that you don't have to =).

**Comment by JedWatson** [comment]
Thanks @chenglou 

> Passing null crashes it

Is this desired behaviour??

> Empty class names return undefined rather than ''

Ditto

> it'd be nice if this could be classNames camelCased

Do you mean camelCase the name of the package in npm?

**Comment by chenglou** [comment]
1. Nope.
2. Don't think so.
3. Don't think you can actually change it? In which case, nvm.

Made a new PR that fixes these ^
