### ISSUE TITLE
Add de-duping functionality

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/classnames#31]
There are two competing PRs to add deduping functionality for `classNames`.

I'm happy to add support for it but not to impact the performance of the package, so what I propose we do is add one as `./dedupe.js`.

Anyone who then needs deduping can simply `require('classnames/dedupe')` and get the alternate version. This has the added benefit of not increasing the download size, whether in browserify or standalone distributions.

@dcousens would appreciate your help assessing #20 vs. #21 in terms of which one we should merge.

From my assessment, #21 is missing some edge cases because it doesn't split strings, so the following test would fail:

`asset.equal(classNames('a b', { a: false, b: true }), 'b')`

#20 also uses a separate `_parse` function which may be more efficient than the closure used in #21... needs some testing.

**Comment by dcousens** [comment]
> From my assessment, #21 is missing some edge cases because it doesn't split strings, so the following test would fail ...

That is what I found as well.
I think #21 is the best candidate, granted the tests could also be simplified.

As mentioned, we should pull the de-dupe implementation out to a separate file (`dedupe.js`) after merge.

**Comment by JedWatson** [comment]
PRs merged, ready to clean up and release.

**Comment by JedWatson** [comment]
Outstanding tasks to clean up `dedupe`:

- wrap with IIFE so that utility variables and `_parse` function don't bleed into the global scope when the script is simply included in a page
- move strict mode inside the IIFE so it doesn't affect other scripts when concatenated, ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
- use `Array.isArray` as per change in `2.0.0`

I'm on these now.

**Comment by JedWatson** [comment]
Just released 2.1.0 with this included.
