### ISSUE TITLE
[Question] When I used Object's value to computed key, what happened?

### ISSUE THREAD

**Issue by myway8907** [JedWatson/classnames#310]
If there is an object liken this
`const obj = {"key1": 540}`

And I used key1's value to classNames() computed key like this
```
<div className={classNames("some css properties", { [`w-[${obj.key1}px]`]: true})}>...</div>
```
But, that code is not working.

hmm...please explain what I am misunderstanding.
I think postcss is not parsing properly because I used the wrong way in the process of parsing the className.

Please explain the parsing process or other technical aspects. Even after reading the official documentation, I don't understand it well.

**Comment by newyork-anthonyng** [comment]
> But, that code is not working.

@myway8907 Can you tell us what you expect the code to do?

**Comment by myway8907** [comment]
Oops...I've done mistake...

As the day progresses, I can see my serious error on this question.
