### ISSUE TITLE
Vulnerable dependencies (indirect security issues)

### ISSUE THREAD

**Issue by RahatFatimah** [JedWatson/classnames#314]
Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are over 3 vulnerable dependencies present. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the package-lock file I scanned: https://vulert.com/vuln-scan/list/295a98d0-42c2-493d-8d3b-39cb49aa5a9f

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

P.S. this is the lock file i scanned: https://github.com/JedWatson/classnames/blob/main/package-lock.json

Thank you.

**Comment by dcousens** [comment]
This package doesn't have any dependencies, see https://github.com/JedWatson/classnames/blob/main/package.json
