### ISSUE TITLE
locationhttps://media.flis8-1.fna.whatsapp.net/v/t62.7118-24/33324852_1115643886071656_1008534436309328315_n.enc?ccb=11-4&oh=01_AdQ2LEWfQW3ZeVQs3N2d_byGO4Zq-M9C5KcEbbtIxuxBwQ&oe=6560B7CB&_nc_sid=000000&hash=FgoTW9QTzvk1nRpkvMdeNi0rQu_oqVmwfE45spp0c_0%3D&mode=auto&mms-type=image&__wa-mms=#:~:text=The%20webpage%20at,new%20web%20address.

### ISSUE THREAD

**Issue by nreeh456444** [JedWatson/classnames#320]
https://media.flis8-1.fna.whatsapp.net/v/t62.7118-24/33324852_1115643886071656_1008534436309328315_n.enc?ccb=11-4&oh=01_AdQ2LEWfQW3ZeVQs3N2d_byGO4Zq-M9C5KcEbbtIxuxBwQ&oe=6560B7CB&_nc_sid=000000&hash=FgoTW9QTzvk1nRpkvMdeNi0rQu_oqVmwfE45spp0c_0%3D&mode=auto&mms-type=image&__wa-mms=#:~:text=The%20webpage%20at,new%20web%20address.

**Comment by dcousens** [comment]
Sigh, I can't find how to report spam on GitHub
