### ISSUE TITLE
Can we add exports field for this package?

### ISSUE THREAD

**Issue by krutoo** [JedWatson/classnames#321]
Hi,  i try to use classnames in nodejs and i need to import `classnames/bind` but not `classnames/bind.js` (because of my bundler config)

can we add something like this:
```json
{
  "exports": {
    ".": {
      "default": "./index.js"
    },
    "./bind": {
      "default": "./bind.js"
    },
    "./dedupe": {
      "default": "./dedupe.js"
    }
  },
}
```

in package.json of classnames?

**Comment by jonkoops** [comment]
I think this is a good idea, it's certainly where modern package development is going. In my experience applying this field it is a breaking change due to inconsistent behaviour of tools that consume it, so I will mark it as such.

**Comment by jonkoops** [comment]
Yes, that is possible, but in practice I have had several bug reports on other packages I maintain when this field was introduced. Nothing wrong with putting this in a major version.

My intention is to try and fix all the existing open issues and then move to the tasks that would involve a potential major version bump such as this one.

**Comment by jonkoops** [comment]
Upon closer consideration, I do believe we could attempt to land this as a non-breaking change. Theoretically, if the exported surface is equivalent to that which is currently exposed, this should work as expected. I am going to give this a shot.
