### ISSUE TITLE
Need a maintainer?

### ISSUE THREAD

**Issue by jonkoops** [JedWatson/classnames#323]
Hi, I see that activity on the repo is quite infrequent. If you like you can add me as a collaborator and I can help clean up the backlog and resolve some issues and PRs. Let me know :)

cc @dcousens @JedWatson

**Comment by JedWatson** [comment]
@jonkoops thanks for the offer, that sounds great. I'll add you now, welcome to the team!

**Comment by jonkoops** [comment]
Great, just accepted the invite, I will close this issue! Just FYI I will be on the road for the next couple of days, but I will try to get more active after that.

**Comment by dcousens** [comment]
Thanks @jonkoops, I'm happy to help review anything if you're wanting a second pair of eyes

**Comment by jonkoops** [comment]
Great, yeah let's peer up!

**Comment by jonkoops** [comment]
@dcousens @JedWatson could either of you give me right to publish a new version? One of the workflows for release is currently [pending for approval](https://github.com/JedWatson/classnames/actions/runs/7287559066).

**Comment by dcousens** [comment]
@jonkoops approved!
If you're OK with flagging me when ready (on this issue or?) I'll try and keep up for now :yellow_heart: 

Unfortunate that I don't receive a GitHub notification for pending action...

**Comment by jonkoops** [comment]
Sure, we can keep using this issue as a means, or I can log a new one when we need a release Looks like this one went off without a hitch!. Thanks so much for the retro-active reviews :pray:
