### ISSUE TITLE
Import from 'classnames' broken since v2.5.0

### ISSUE THREAD

**Issue by marneau** [JedWatson/classnames#358]
Hello 👋 We are using classnames into our project and we have just made an upgrade from v2.3.2 to v2.5.1 - we are facing the following issue: 
```
./node_modules/classnames/index.js
Module parse failed: Cannot use 'import.meta' outside a module
```

After investigation, it seems to be coming directly from the module import which we are importing the following way: 
```
import cx from 'classnames'
```

It is also happening on v2.5.0 but not v2.4.0.

After having a quick look around at recently merged PRs, I have a hunch it could be coming from [the type being moved to 'commonjs' instead of a 'module'](https://github.com/JedWatson/classnames/pull/342/files#r1437193901) but as I said, this is just a wild guess :) 

Would you be able to advise on this by any chance?

**Comment by jonkoops** [comment]
Can you provide a little more information about how to reproduce this issue? What runtime are you using? What version of said runtime? Please provide a minimal an reproducible piece of example code.

**Comment by jonkoops** [comment]
Closing this for a lack of information to reproduce the issue, if you have a reproducible case let us know.

**Comment by jonkoops** [comment]
@kingsley-sunny if you have a reproducible case please file a new issue with minimal steps to reproduce.
