### ISSUE TITLE
Adding classnames to package.json

### ISSUE THREAD

**Issue by cassidoo** [JedWatson/classnames#39]
`npm install classnames` should add this to package.json, right now it doesn't.

At this point, were someone to want to put it in package.json themselves, would they just add `"classnames": "*"`?

**Comment by jruhland** [comment]
What your'e looking for is `npm install --save classnames` or `npm install --save-dev classnames` to add it to your package.json

**Comment by koulmomo** [comment]
@cassidoo as per the `npm` docs, `npm install classnames` will **NOT** add it to your `package.json` (as is intended). You need to use the [`--save` flag](https://docs.npmjs.com/getting-started/installing-npm-packages-locally#using-package-json-and-the-save-flag) for it to do that.

ie: 
```sh
$ npm install classnames --save
```

Also, as a general rule, you almost **NEVER** want to set a `*` for your dependencies (`*` means download ANY version of the package, which is dangerous)

At the very least, you should **fix** the major version of the package you are downloading to protect yourself from breaking changes (in this case `^2.1.2`).

see [semver.npmjs.com](http://semver.npmjs.com/) for more info on package ranges etc...

**Comment by cassidoo** [comment]
Ah gotcha.  I was going off of this file: https://github.com/JedWatson/classnames/blob/master/benchmarks/package.json

Thank you very much! :+1:
