### ISSUE TITLE
Add possibility to build classname based on string

### ISSUE THREAD

**Issue by oleronning** [JedWatson/classnames#42]
I would really like the possibility to build a class name from a variable if the said variable is set. I encountered the issue when building classes for a standard Bootstrap alert box: in addition to the class `alert` I also needed the string `alert-<alert-type>`, but only if `alert-type` is defined.

**Comment by dcousens** [comment]
@oleronning can you give an example of how you think this would work?

**Comment by oleronning** [comment]
@dcousens based on your current implementation, this may not be straigh forward, but one possible solution is to pass an object as a parameter like so:
```javascript
{
  'substrings': ['alert-', alert_type],
  'build_string': typeof(alert_type) !== 'undefined'
}
```
This was my first thoughts, but I'm not suprised if there is an more elegant/effective way of doing it.

Thanks!

**Comment by dcousens** [comment]
@oleronning and the resultant string would be?

**Comment by oleronning** [comment]
@dcousens if `var alert_type = 'warning'` the resultant string would be `alert-warning`

**Comment by dcousens** [comment]
Why wouldn't you just use `{ "alert-warning": typeof(alert_type) !== 'undefined' }`.

**Comment by oleronning** [comment]
Because `alert_type` is passed to my method as an argument, and might just as well be `danger` or `success`

**Comment by ojame** [comment]
We're using ES6's [computed values](http://wiki.ecmascript.org/doku.php?id=harmony:object_literals#object_literal_computed_property_keys) (Babel, of course):

```
{
   styles.Bar: true,
   [this.props.className]: this.props.className,
}
```

**Comment by oleronning** [comment]
@ojame Sweet! Thanks a lot!

**Comment by dcousens** [comment]
@ojame of course,  @oleronning this is definitely the way to do this.  Lets not over-complicate this module which is essentially a language hitch.

Thanks @ojame
