### ISSUE TITLE
accept computed variables as class name

### ISSUE THREAD

**Issue by benrlodge** [JedWatson/classnames#46]
Is there a way to include a computed variable, not just a string? For example below, is there a way I can include `typeName`, `prefix`, and `forIcon` if they pass the truth tests?

```javascript
  getClassNames() {
    const typeName = `${this.props.type}-${this.props.name}`;
    const prefix = this.props.prefix + '-';
    const forIcon = ICON_LIST[this.props.for];
    
    return classnames([
      'muted-message',
      this.props.classNames,
      this.props.type,
      {typeName: this.props.type},
      {prefix: this.props.prefix},
      {forIcon: this.props.for}
    ]);
  }
```

**Comment by WickyNilliams** [comment]
ES6 allows for [computed property names/keys on object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_6). So this should work (assuming use of babel or some other transpiler):

```js
return classnames([
      'muted-message',
      this.props.classNames,
      this.props.type,
      {[typeName]: this.props.type},
      {[prefix]: this.props.prefix},
      {[forIcon]: this.props.for}
    ]);
```

**Comment by benrlodge** [comment]
nice, thanks @WickyNilliams.

**Comment by WickyNilliams** [comment]
No problems :)
