### ISSUE TITLE
help required: classNames with 'props'

### ISSUE THREAD

**Issue by ssjogus** [JedWatson/classnames#65]
hi,

thanks for wonderful add-on. question that I have is, can i use it with props? can i check conditionally what props value component has, and then add the class?
e.g:
```
  var btnClass = classNames({
      'btn btn-sm': true,
      'btn-success': this.props.flag.success,
      'btn-warning': this.props.flag.warning
    });
  return <button className={btnClass}  >{this.props.label}</button>;
//-----------------
  <Button label='click here'  flag='success'/>
  <Button label='click here'  flag='warning'/>
```

Thanks for help

**Comment by longlho** [comment]
yeah I don't see why not

**Comment by ssjogus** [comment]
Somehow when i try to set 'className' depending on the 'props' 

```
//..
 return <button className={btnClass}  >{this.props.label}</button>;
//..
 <Button label='click here'  flag='success'/>
 <Button label='click here'  flag='warning'/>
```

it gives both the classes to both the buttons..

Html it is creating is this like this. Shouldn't one button have 'btn-success' and another one have 'btn-warning' classes. Or do i need to create for each button different variables?

```
<button class="btn btn-sm btn-success btn-warning" data-reactid=".0.$=12">click here</button>
<button class="btn btn-sm btn-success btn-warning" data-reactid=".0.$=12">click here</button>
```


![image](https://cloud.githubusercontent.com/assets/8896732/12015798/acbe1a1a-ad67-11e5-83da-3e6c92c698aa.png)

**Comment by JulienMelissas** [comment]
@ssjogus if you're using ES6 you can use template strings and this should simply things and work great:

```
var btnClass = classNames('btn', 'btn-sm', {
  `btn-${this.props.flag}`: this.props.flag,
});
```

**Comment by JulienMelissas** [comment]
But if you're wondering why your code up there didn't work, I think you need to check for the string you're passing in: `'btn-success': this.props.flag === 'success'` not `'btn-success': this.props.flag.success`

**Comment by ssjogus** [comment]
hi @JulienMelissas ,

thanks for your answer..i was writing it in wrong way..

your answer **'btn-success': this.props.flag === 'success'**

worked really well. 

thanks once again..

**Comment by jasonwbullok** [comment]
@JulienMelissas Template literals can't actually be used as a key in an Object literal. A computed property should be used:

var btnClass = classNames('btn', 'btn-sm', {
  ['btn-' + this.props.flag]: this.props.flag
});

See: [Using a variable for a key in a JavaScript object literal](http://stackoverflow.com/questions/2274242/using-a-variable-for-a-key-in-a-javascript-object-literal)
