### ISSUE TITLE
Issue with classes on list items.

### ISSUE THREAD

**Issue by smsenesac** [JedWatson/classnames#68]
I'm trying to use classnames to manage the active class on a list of bootstrap tabs (see the code below).  However, the generated markup is putting the active class on the anchor link child of the list item instead of the list item itself which causes the currently active tab to not display correctly.  Is there something that I'm doing incorrectly?

```javascript
    const myFeedTabClasses = classNames({ active: this.state.selectedTab === 'my-feed' });
    const discoveryFeedTabClasses = classNames({ active: this.state.selectedTab === 'discovery-feed' });

    return (
      <section id="feed">
        <section id="content-region">
          <PostCreationBox />

          <ul className="nav nav-tabs" role="tablist">
            <li role="presentation" className={myFeedTabClasses}>
              <Link to={Config.RouteNames.MY_FEED} role="tab" onClick={this._onSelectMyFeed}>Feed</Link>
            </li>
            <li role="presentation" className={discoveryFeedTabClasses}>
              <Link to={Config.RouteNames.DISCOVERY_FEED} role="tab" onClick={this._onSelectDiscoveryFeed}>
                Discovery Feed
              </Link>
            </li>
          </ul>

          <RouteHandler user={this.props.user} />
        </section>
      </section>
    );
```

**Comment by dcousens** [comment]
Your use of `classNames` is fine.   Why not just check (`console.log(myFeedTabClasses`) to find out what the values are?
If it is not `active` when `selectedTab === `my-feed`, then, that is a bug you should report, but I suspect that it is not the case.
