### ISSUE TITLE
Feature request - render to selector syntax

### ISSUE THREAD

**Issue by kumavis** [JedWatson/classnames#69]
current format: `class-a class-b`

selector format: `.class-a.class-b`

**Comment by kumavis** [comment]
basically just
```js
toSelectorFormat(str){
  return '.'+str.split(' ').join('.')
}
```

**Comment by dcousens** [comment]
I don't think that is in scope of this library.

It might be better to have an alternative, internal module: `classnames/custom` or something, where you could specify these advanced options.
