### ISSUE TITLE
Later param has priority?

### ISSUE THREAD

**Issue by ddhp** [JedWatson/classnames#71]
Hi, thanks for this very useful library, it's gave me huge convenience manipulating DOM classes!

While using classnames, I found out it's somehow a bit inconvenient to remove class from current DOM class context, e.g
I am dealing with following html:
```html
<p class="my-text invisible"></p>
```
and I want to remove invisible but keep my-text class:
```js
var pDOM = document.querySelector('.my-text');
var classNames = require('classnames');
function showP {
  var pDOMClass = classNames(pDOM.className, {invisible: false});
  pDOM.className = pDOMClass;
}
showP();
```
currently it will still keep `invisible` class b/c it's set in HTML, and pDOMClass is 'my-text invisible'.

Why I need this feature is b/c I don't want to specify `my-text` inside script, but get reference from HTML.

So is it feasible to take later param with higher priority?

**Comment by razh** [comment]
This is available as `classnames/dedupe`.

https://github.com/JedWatson/classnames#alternate-dedupe-version

```js
var classNames = require('classnames/dedupe');

classNames('foo', 'foo', 'bar'); // => 'foo bar'
classNames('foo', { foo: false, bar: true }); // => 'bar'
```

**Comment by ddhp** [comment]
Oh I totally missed that part in Readme :p, thanks for your reply!
