### ISSUE TITLE
Global styles. 

### ISSUE THREAD

**Issue by ramakay** [JedWatson/classnames#74]
Say I have grid styles - I do not want this to be packaged with every component - any thoughts on how to approach this

**Comment by ptim** [comment]
Not sure if I understand the question, or if this question is actually specific to classnames.. 

One interpretation of the question is:

```sass
// global scss stylesheet
.quarter-grid-item {
    @extend .col-xs-12;
    @extend .col-sm-6;
    @extend .col-md-3;
}
```

```js
<GridItem className="quarter-grid-item"></GridItem>;
```
http://www.sitepoint.com/sass-semantically-extend-bootstrap/

This might relate to be use with classnames like so:
```js
var classNames = require('classnames');

var Button = React.createClass({
  // ...
  render () {
    var colClass = classNames('quarter-grid-item', {
      'is-selected': this.state.isSelected
    });
    return <GridItem className={colClass}></GridItem>;
  }
});
```

hth!

**Comment by JedWatson** [comment]
@ramakay hopefully @ptim's answer helps you out - I'm going to close this but if I've misunderstood how the question is specific to classnames, let us know!
