### ISSUE TITLE
upgrade react version 15.0.1 

### ISSUE THREAD

**Issue by redkyo017** [JedWatson/classnames#75]
when I upgraded React to version 15.0.1(newest version) I got this error: classnames@2.2.3 - UNMET PEER DEPENDENCY react@15.0.1.
Need some help !, thanks.

**Comment by JedWatson** [comment]
That's really weird - I suspect npm is telling you fibs. This package has no dependencies, and doesn't use react at all...

**Comment by redkyo017** [comment]
After I updated the NPM version ,this error's gone.
Thank you a lot, JedWatson.

**Comment by JedWatson** [comment]
Glad to hear it!

**Comment by jmz7v** [comment]
Hi, I'm trying to install classnames and I'm getting the same error as @redkyo017.
```
├── query-string@4.1.0  extraneous
├── UNMET PEER DEPENDENCY react@15.0.2
├── UNMET PEER DEPENDENCY react-dom@15.0.2
└── UNMET PEER DEPENDENCY react-tap-event-plugin@1.0.0
```
I cleaned my npm cache and updated npm to the latest version (and react@15.0.2) and still refuses to install, I find it interesting that classnames doesn't have dependencies and I'm still getting this error, should I report this error to npm?

**Comment by jmz7v** [comment]
Oh, I ran `npm prune` to remove `query-string` and I was finally able to install `classnames`, weird since I had no problem with `query-string` being in there until now.
