### ISSUE TITLE
Proposal: Have a option to prefix or suffix the classnames on className

### ISSUE THREAD

**Issue by davesnx** [JedWatson/classnames#80]
Hi @JedWatson,

I'm actually thinking that would be useful to have a option for specify a prefix/suffix of all the classes that are you passing into the `classNames()` and have it as a global defined variable.

like:

``` js
classNames.prefix('foo-')
```

Have a little bit more of API in terms of options or settings for some cases can be useful.
What do you think guys? 

PS: I this goes forward I would create the PR with some proposal.

**Comment by dcousens** [comment]
``` javascript
'abstract fizz buzz'.split(' ').map(x => 'foo-' + x).join(' ')
```

You could do it,  it might be more performant... but IMHO,  its probably out of scope.

**Comment by davesnx** [comment]
Of course I can do it without classNames, are just string operations.
The discussion that I try to open is have some options like that inside the api of classNames, and abstract this operations/options on the correct place, instead of running it each time that I want it. @dcousens

**Comment by springuper** [comment]
ask for this feature. it's very useful when building ui library without css-modules.

**Comment by davesnx** [comment]
Seems that isn't aligned with the purpose of this module and with a preset you could achive the same.

I'm closing this...

**Comment by maestrow** [comment]
I'm looking for the same feature in this module and came here. @davesnx, It would be helpful for me and other searching people, if you give a little description - with what preset we could achieve the same? Thanks.

**Comment by davesnx** [comment]
I came up with a babel-plugin to prefix CSS classes instead, I went for a build-time solution rather than a run-time.
