### ISSUE TITLE
Webpack Warning - There is another module with equal name when case is ignored

### ISSUE THREAD

**Issue by AndyOGo** [JedWatson/classnames#82]
My Webpack build logs the following warning:

> WARNING in ./~/classNames/index.js
> There is another module with an equal name when case is ignored.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Rename module if multiple modules are expected or use equal casing if one module is expected.

I checked the webpack repo and they have a related issue [#382](https://github.com/webpack/webpack/issues/382)

Is use ES2015 module syntax as follows:

``` js
import classNames from 'classnames';
```

I quickly checked your code and found two possible parts causing this warning:
- it exports two additional variations (dedupe and bind) as the same name.
- The module names used to export as AMD and CommonJS Syntax are not consistent - `classNames` vs. `classnames`

**Comment by AndyOGo** [comment]
Okay I investigated the issue more carefully. As it turns out it is quite simple.
Just use the CommonJS module key:

````js
import classNames from 'classNames';
````

I leave it open, because inconsistency in module names for different module syntax is a bad practise.

**Comment by stevemao** [comment]
probably better to keep it all lowercased `classname`.

**Comment by dcousens** [comment]
> probably better to keep it all lowercased classname.

Agreed,  but that is now a massive breaking change for anyone using bower.

**Comment by AndyOGo** [comment]
Agree, it is definitely a breaking change. So I would put it in a Major release.

**Comment by dcousens** [comment]
I vote the AMD exports are removed entirely; then this is a non-issue.

**Comment by anilanar** [comment]
Assuming most people have now switched to ES imports, why doesn't `classnames` have an ES6 main file using `module` key in `package.json`? `module.exports` can be mapped to ES in 2 different ways (wildcard import and default import) which causes issues if used in a complicated scenarios with typescript, babel, node etc.

**Comment by a932455223** [comment]
The issue help me  solve my problem.Thanks.

**Comment by dcousens** [comment]
Probably resolved by https://github.com/JedWatson/classnames/pull/150,  closing in favour of that
