### ISSUE TITLE
[CSS Modules] Multiple binds in same component?

### ISSUE THREAD

**Issue by kevinSuttle** [JedWatson/classnames#83]
Is the following possible? I cannot seem to get it to work.
```js
let inputClasses = classNames.bind(inputStyles);
let labelClasses = classNames.bind(labelStyles);
let inputClassList = inputClasses({
  inputField: true,
  preValidated: this.state.focused,
});

let validationMessageClassList = labelClasses({
  errorLabel: true,
  postValidated: !this.state.focused,
});
```
```jsx
<TextInput className={inputClassList} />
<ErrorLabel className={validationMessageClassList} />
```

For some reason, the styles appear in React Dev Tools, but not in the DOM. 
Look for `postValidate` in the following screenshots. It only appears in RDT.

<img width="1440" alt="screen shot 2016-05-20 at 5 07 37 pm" src="https://cloud.githubusercontent.com/assets/95672/15442197/7bc4b448-1ead-11e6-8a05-ff481a837aa9.png">

<img width="1439" alt="screen shot 2016-05-20 at 5 07 57 pm" src="https://cloud.githubusercontent.com/assets/95672/15442201/8714d31e-1ead-11e6-9f3a-bc457d3e9058.png">

**Comment by koulmomo** [comment]
try

```js
let inputClasses = classNames.bind(null, inputStyles);
let labelClasses = classNames.bind(null, labelStyles);
```

**Comment by kevinSuttle** [comment]
That actually broke it. 

How I fixed it: 
made sure the presentational components did not have `className`s, **except for** `props.className`. Then, in the container component, I just used the syntax above.
