### ISSUE TITLE
how to write nest class selector when use classnames?

### ISSUE THREAD

**Issue by shikelong** [JedWatson/classnames#84]
Just like this.
```css
.class1>.class2 {

}

```

both class1 and class2 would be add a hash suffix.

so the nest class selector not work.

Regards.

**Comment by JedWatson** [comment]
@shikelong I'm having trouble understanding what you mean by this... classnames is just responsible for conditionally joining strings based on truthy/falsy values. Can you include the JavaScript code from your implementation to explain the use case further?
