### ISSUE TITLE
Should this provide a UMD / minified version?

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/classnames#9]
Since it's published to Bower (#7) some people may just want to be able to drop it into their page, so we'll need to include a build (via browserify / web pack) for that. Might be nice to dist a .min version too, even though it's _tiny_.

@chenglou thoughts?

**Comment by JedWatson** [comment]
I wrapped a simple try/catch around the export statement, not a proper solution but this way if it's included directly it'll expose a global `classNames` function and not throw an error if `module` is undefined.

**Comment by chenglou** [comment]
Here's how I do it: https://github.com/chenglou/react-treeview/blob/master/react-treeview.jsx

Also, I don't usually provide a min inside repo too. Bower users will probably just add that to the list of things they need to minify anyways.

**Comment by JedWatson** [comment]
Started borrowing your code from `react-treeview` but it's so much simpler because I don't need React defined, so I just changed it to a simple `if (module && module.exports)` check. I think that covers enough cases and agree about magnification.

Feel free to open a PR if you've got a better way... otherwise, thanks :)

**Comment by marcfallows** [comment]
I think it would be really great if an `npm install classnames` provided us with an `index.min.js`. That is pretty common practice. Yes it's tiny, but could be even tinier 🙂

**Comment by dcousens** [comment]
@marcfallows why?
I'd prefer a source code I can debug and let my own build system minify.
