### ISSUE TITLE
Class name not always rendering the same

### ISSUE THREAD

**Issue by jwilkinson** [JedWatson/classnames#93]
I have the following code 

```
function renderSuggestion(suggestion, { query }) {
  return (
      <Link to={suggestion.url} target="_self">
          <div>{suggestion.title}</div>
          <div className={cx("suggestionSubtitle")}>{suggestion.subtitle}</div>
      </Link>
  );
}

function renderSectionTitle(section) {
  return (
    <div>
        <span className={cx(getIconForSection(section.title) + ' font16')}></span>
        <span className={cx("sectionIcon")}><strong>&nbsp;{section.title}</strong></span>
    </div>
  );
}
```

The first function the cx renders correctly with the prefix the second one, renders just what is in the quotes.

What am I doing wrong?

**Comment by dcousens** [comment]
@jwilkinson someone may be able to help you,  but this certainly isn't related to the `classnames` package?

**Comment by jackmarchant** [comment]
@jwilkinson if you change `<span className={cx(getIconForSection(section.title) + ' font16')}></span>` to `<span className={cx(getIconForSection(section.title), ' font16')}></span>` that should work?
