### ISSUE TITLE
Question regarding production bundling

### ISSUE THREAD

**Issue by loopmode** [JedWatson/classnames#95]
Hi. I'm tinkering with webpack DLLPlugin lately. I just wondered... Does classnames perform its magic at compile time or at run time?
I use the module in almost all my react classes, so I definitely want it "preloaded" or at least available at runtime, that's what I thought at least.
Now I wonder: should I bundle the classnames module into a vendors DLL (or any kind of webpack chunk that gets preloaded), or is it just wasted there since it performed its magic during the compilation step?

Sorry if this has already been answered elsewhere..

**Comment by dcousens** [comment]
@loopmode it runs at runtime,  unfortunately,  ha.

**Comment by loopmode** [comment]
Ok, so definitely bundle it and also put it in a commons chunk. Thanks
