### ISSUE TITLE
Undefined computed keys

### ISSUE THREAD

**Issue by artisologic** [JedWatson/classnames#96]
HI,

First, thanks for your amazing package, we use it all over the place and it's been truly great.

We have recently discovered a slight limitation with regards to dynamic keys in objects passed to `classNames`.
#### Example:

Say we have a React Button component which receives a `theme` object.

``` jsx
function Button({ theme, disabled, children, ...otherProps }) {
    const rootClass = classNames(theme.button, {
        [theme.disabledButton]: disabled
    });

    return (
        <button
            className={rootClass}
            disabled={disabled}
            {...otherProps}
        >
            {children}
        </button>
    );
}
```

If the provided theme object doesn't contain a key of `disabledButton`, `[theme.disabledButton]` will be coerced into a string producing a key of `"undefined"`.

This means that the DOM element will actually receive a class of `"undefined"`.

The fix would be a simple one. On this line (https://github.com/JedWatson/classnames/blob/master/index.js#L28)

``` diff
- if (hasOwn.call(arg, key) && arg[key]) {
+ if (hasOwn.call(arg, key) && key !== 'undefined' && arg[key]) {
```

There are ways around it obviously, but I was wondering if you would be interested in a fix at all? Or if you would consider that this is not the responsibility of the library and we should make sure we provide defined keys.

For information this is how we currently get around it:

``` jsx
const rootClass = classNames(theme.button, {
    [theme.disabledButton]: disabled && theme.disabledButton
});
```

Let me know how you feel about this, and thanks again for your work.

**Comment by peduarte** [comment]
+1

**Comment by t1mmen** [comment]
This is probably related to errors we're seeing at Timely (reported via getsentry) for IE11 users:

`Unable to get property 'contains' of undefined or null reference`

**Comment by dcousens** [comment]
`undefined` could be a css classname.
I don't think we should trash it just because users made a mistake.

But,  that is just my opinion.   I'll defer on the topic, but,  going to close unless someone wants to take it up.
