### ISSUE TITLE
[Question] is it possible to have separate ES modules exports

### ISSUE THREAD

**Issue by btd** [JedWatson/classnames#99]
Hello.

I am building most of my frontend libs with rollupjs and single non-convertable library is this one. Is it possible to have a separate version with es2015 modules exports? I can create PR if you tell me your preference about handling and support.

Thanks.

**Comment by dcousens** [comment]
@btd do you mean you want a copy of the library using `export`/`import`?
I don't think that will be a simple thing to maintain... at all

**Comment by btd** [comment]
@dcousens Thanks for looking. Actually it is very simple if you care. You have each js file with import and export. Before publishing you use tool like rollup or babel to convert modules to UMD format used now (actually amd defined bad).
For other people comming there you can use for now `classnames-es` package.

**Comment by dcousens** [comment]
> Before publishing you use tool like rollup or babel to convert modules to UMD format used now (actually amd defined bad).

And there is the kicker.  That isn't simple,  and can be a pain to keep up to date.

**Comment by dcousens** [comment]
> For other people comming there you can use for now classnames-es package.

@btd maybe you can make a PR to put that in the README?

**Comment by dcousens** [comment]
Unless @JedWatson wants to make a `classnames/es` file.

**Comment by jedmao** [comment]
I was having problems importing this module into TypeScript for this very reason. Changing the export code in this library to the following fixes it:
```js
		Object.defineProperty(exports, "__esModule", { value: true });
		exports.default = classNames;
```
Now I can import with:
```ts
import classnames from 'classnames';
```
But I have to add the compiler flag `--allowSyntheticDefaultImports` to make that work, because the TypeScript definitions don't declare a default export.

Related to https://github.com/JedWatson/classnames/pull/103

**Comment by yinghaochan** [comment]
webpack hack to add exports.default:

` webpack.config.module.rules.push({ test: /classnames/, use: ['exports-loader?default=module.exports'] })`

**Comment by dlindenkreuz** [comment]
@jedmao You can use classnames in TypeScript without `--allowSyntheticDefaultImports` like this:

```ts
import * as cx from "classnames"
```
